export const MOmess = {
    "additions": [
        {
            "alias": "别名",
            "appCode": "所属业务应用编码",
            "appMode": "string",
            "appName": "string",
            "appRoleGroup": "string",
            "branchName": "zh",
            "branchNameCn": "string",
            "createdByTool": "string",
            "description": "string",
            "discoveryIP": "10.218.32.71",
            "ecBizIP": "string",
            "ecDomainName": "string",
            "firstClass": "NETWORK",
            "firstSecArea": "开发测试域",
            "hostname": "string",
            "instance": "string",
            "ipv6": "string",
            "keyword": "10.218.32.71",
            "location": "string",
            "managedStatus": "纳管",
            "mappingIP": "string",
            "mngtOrg": "string",
            "mngtOrgCode": "zh",
            "monitorStatus": "string",
            "name": "测试001",
            "netDomain": "string",
            "objectID": "string",
            "onlineStatus": "在线",
            "secondClass": "SWITCH",
            "secondSecArea": "互联网公众服务测试区，这一级的值可能为空",
            "thirdClass": "NET_INTF",
            "uniqueCode": "string",
            "uuid": "095be615-a8ad-4c33-8e9c-c7612fbf6c9f"
        },
        {
            "alias": "别名2",
            "appCode": "所属业务应用编码",
            "appMode": "string",
            "appName": "string",
            "appRoleGroup": "string",
            "branchName": "zh",
            "branchNameCn": "string",
            "createdByTool": "string",
            "description": "string",
            "discoveryIP": "10.218.32.11",
            "ecBizIP": "string",
            "ecDomainName": "string",
            "firstClass": "NETWORK",
            "firstSecArea": "开发测试域",
            "hostname": "string",
            "instance": "string",
            "ipv6": "string",
            "keyword": "10.218.32.11",
            "location": "string",
            "managedStatus": "纳管",
            "mappingIP": "string",
            "mngtOrg": "string",
            "mngtOrgCode": "bj",
            "monitorStatus": "string",
            "name": "测试001",
            "netDomain": "string",
            "objectID": "string",
            "onlineStatus": "在线",
            "secondClass": "SWITCH",
            "secondSecArea": "互联网公众服务测试区，这一级的值可能为空",
            "thirdClass": "NET_INTF",
            "uniqueCode": "string",
            "uuid": "095be615-a8ad-4c33-8e9c-c7612fbf6c55"
        }
    ],
    "agentGetFails": [
        "string"
    ],
    "agentPingFails": [
        "string"
    ],
    "branch": "string",
    "changeType": "ON",
    "exists": [
        {
            "alias": "存在别名",
            "appCode": "所属业务应用编码",
            "appMode": "string",
            "appName": "string",
            "appRoleGroup": "string",
            "branchName": "BJ",
            "branchNameCn": "string",
            "createdByTool": "string",
            "description": "string",
            "discoveryIP": "10.120.110.119",
            "ecBizIP": "string",
            "ecDomainName": "string",
            "firstClass": "NETWORK",
            "firstSecArea": "开发测试域",
            "hostname": "string",
            "instance": "string",
            "ipv6": "string",
            "keyword": "10.120.110.119",
            "location": "string",
            "managedStatus": "纳管",
            "mappingIP": "string",
            "mngtOrg": "string",
            "mngtOrgCode": "BJ",
            "monitorStatus": "string",
            "name": "测试002存在",
            "netDomain": "string",
            "objectID": "string",
            "onlineStatus": "在线",
            "secondClass": "SWITCH",
            "secondSecArea": "互联网公众服务测试区，这一级的值可能为空",
            "thirdClass": "NET_INTF",
            "uniqueCode": "string",
            "uuid": "095be615-a8ad-4c33-8e9c-c7612fbf6c9f"
        }
    ],
    "moType": "OS",
    "requestMsg": "string"
}

export const monitorExists = {
    "exists": [
        {
            "alias": "别名",
            "appCode": "所属业务应用编码",
            "appMode": "string",
            "appName": "string",
            "appRoleGroup": "string",
            "branchName": "zh",
            "branchNameCn": "string",
            "createdByTool": "string",
            "description": "string",
            "discoveryIP": "10.218.32.71",
            "ecBizIP": "string",
            "ecDomainName": "string",
            "firstClass": "NETWORK",
            "firstSecArea": "开发测试域",
            "hostname": "string",
            "instance": "string",
            "ipv6": "string",
            "keyword": "10.218.32.71",
            "location": "string",
            "managedStatus": "纳管",
            "mappingIP": "string",
            "mngtOrg": "string",
            "mngtOrgCode": "zh",
            "monitorStatus": "string",
            "name": "测试001",
            "netDomain": "string",
            "objectID": "string",
            "onlineStatus": "在线",
            "secondClass": "SWITCH",
            "secondSecArea": "互联网公众服务测试区，这一级的值可能为空",
            "thirdClass": "NET_INTF",
            "uniqueCode": "string",
            "uuid": "095be615-a8ad-4c33-8e9c-c7612fbf6c9f"
        }
    ],
    "notExists": [
        {
            "alias": "别名",
            "appCode": "所属业务应用编码",
            "appMode": "string",
            "appName": "string",
            "appRoleGroup": "string",
            "branchName": "zh",
            "branchNameCn": "string",
            "createdByTool": "string",
            "description": "string",
            "discoveryIP": "10.218.32.71",
            "ecBizIP": "string",
            "ecDomainName": "string",
            "firstClass": "NETWORK",
            "firstSecArea": "开发测试域",
            "hostname": "string",
            "instance": "string",
            "ipv6": "string",
            "keyword": "10.218.32.71",
            "location": "string",
            "managedStatus": "纳管",
            "mappingIP": "string",
            "mngtOrg": "string",
            "mngtOrgCode": "zh",
            "monitorStatus": "string",
            "name": "测试001",
            "netDomain": "string",
            "objectID": "string",
            "onlineStatus": "在线",
            "secondClass": "SWITCH",
            "secondSecArea": "互联网公众服务测试区，这一级的值可能为空",
            "thirdClass": "NET_INTF",
            "uniqueCode": "string",
            "uuid": "095be615-a8ad-4c33-8e9c-c7612fbf6c9f"
        }
    ]
}

export const monitroResult = {
    "mt": {
        "appNameAuto": "string",
        "appNameEditing": "string",
        "applicant": "k40333",
        "branch": "string",
        "correlationFeature": "string",
        "createdBy": "string",
        "createdTime": 0,
        "description": "string",
        "enabled": true,
        "filter": {},
        "group": [
            {}
        ],
        "name": "test_20230525",
        "noticed": true,
        "overdue": true,
        "relatedMtId": "a6c6f1aa-a314-41bb-8fcb-873998d6bf75",
        "state": "TO_REVIEW",
        "ticket": "string",
        "timeDef":{"repeatType":"OTHER","range":[{"begin":"2023-05-25 00:00:00","end":"2023-05-26 23:59:59"}]},
        "tpe": "PERIODIC",
        "updatedBy": "string",
        "updatedTime": 0,
        "uuid": "095be615-a8ad-4c33-8e9c-c7612fbf6c9f",
        "whitelist": "string",
        "whitelistEnabled": "string"
    },
    "requestMsg": "string",
    "requestResult": [
        {
            "hostIP": "10.10.10.10",
            "msg": "string",
            "success": "true"
        },
        {
            "hostIP": "10.10.10.20",
            "msg": "string",
            "success": "true"
        },
        {
            "hostIP": "20.10.10.20",
            "msg": "string",
            "success": "false"
        },
        {
            "hostIP": "20.10.10.20",
            "msg": "string",
            "success": "false"
        },
    ],
    "requestSuccess": "string"
}