export default  [
{ value: 'N9K', name: 'N9K' },
{ value: 'N7K', name: 'N7K' },
{ value: 'N5K', name: 'N5K' },
{ value: 'N2K', name: 'N2K' },
{ value: 'C76', name: 'C76' },
{ value: 'C65', name: 'C65' },
{ value: 'C38', name: 'C38' },
{ value: 'C37', name: 'C37' },
{ value: 'C35', name: 'C35' },
{ value: 'ASR1000', name: 'ASR1000' },
{ value: 'CE128', name: 'CE128' },
{ value: 'CE68', name: 'CE68' },
{ value: 'RG-S2628G-I', name: 'RG-S2628G-I' },
{ value: 'NE20E-S8', name: 'NE20E-S8' },
{ value: 'JUNIPER MX', name: 'JUNIPER MX' },
{ value: 'F5', name: 'F5' },
{ value: 'SRX', name: 'SRX' },
{ value: 'ISG1000', name: 'ISG1000' },
{ value: 'SSG550', name: 'SSG550' },
{ value: 'HILLSTONE', name: 'HILLSTONE' },
{ value: 'Huawei USG', name: 'Huawei USG' },
{ value: 'Huawei DDOS', name: 'Huawei DDOS' },
{ value: 'Gigamon NetScout', name: 'Gigamon NetScout' },
{ value: 'Huawei OSN', name: 'Huawei OSN' },
{ value: 'DWDM', name: 'DWDM' },
{ value: 'NSAE', name: 'NSAE' },
{ value: 'Console server', name: 'Console server' },
{ value: 'Juniper VPN', name: 'Juniper VPN' },
{ value: 'MSR', name: 'MSR' },
{ value: 'MP2900', name: 'MP2900' },
{ value: 'MP7500E', name: 'MP7500E' },
{ value: 'S7500', name: 'S7500' },
{ value: 'RSR20', name: 'RSR20' },
{ value: 'MP3900', name: 'MP3900' },
{ value: 'CISCO2900', name: 'CISCO2900' },
]
