export default  [
	{ key: '1', value: 'other' },
	{ key: '2', value: 'regular1822' },
	{ key: '3', value: 'hdh1822' },
	{ key: '4', value: 'ddn-x25' },
	{ key: '5', value: 'rfc877-x25' },
	{ key: '6', value: 'ethernet-csmacd' },
	{ key: '7', value: 'iso88023-csmacd' },
	{ key: '8', value: 'iso88024-tokenBus' },
	{ key: '9', value: 'iso88025-tokenRing' },
	{ key: '10', value: 'iso88026-man' },
	{ key: '11', value: 'starLan' },
	{ key: '12', value: 'proteon-10Mbit' },
	{ key: '13', value: 'proteon-80Mbit' },
	{ key: '14', value: 'hyperchannel' },
	{ key: '15', value: 'fddi' },
	{ key: '16', value: 'lapb' },
	{ key: '17', value: 'sdlc' },
	{ key: '18', value: 'ds1' },
	{ key: '19', value: 'e1' },
	{ key: '20', value: 'basicISDN' },
	{ key: '21', value: 'primaryISDN' },
	{ key: '22', value: 'propPointToPointSerial' },
	{ key: '23', value: 'ppp' },
	{ key: '24', value: 'softwareLoopback' },
	{ key: '25', value: 'eon' },
	{ key: '26', value: 'ethernet-3Mbit' },
	{ key: '27', value: 'nsip' },
	{ key: '28', value: 'slip' },
	{ key: '29', value: 'ultra' },
	{ key: '30', value: 'ds3' },
	{ key: '31', value: 'sip' },
	{ key: '32', value: 'frame-relay' },

]
