import { Select } from 'antd'

export default  [<Select.Option key="activatedBy" value="activatedBy">激活者</Select.Option>,
  <Select.Option key="branchName" value="branchName">分行名字 </Select.Option>,
  <Select.Option key="cabinet" value="cabinet">机柜</Select.Option>,
  <Select.Option key="createMethod" value="createMethod">创建方式</Select.Option>,
  <Select.Option key="createdBy" value="createdBy">创建者</Select.Option>,
  <Select.Option key="createdTime" value="createdTime">创建时间</Select.Option>,
  <Select.Option key="deactivatedBy" value="deactivatedBy">激活者</Select.Option>,
  <Select.Option key="deleteTime" value="deleteTime">删除时间</Select.Option>,
  <Select.Option key="deletedBy" value="deletedBy">删除者</Select.Option>,
  <Select.Option key="description" value="description">描述</Select.Option>,
  <Select.Option key="deviceCode" value="deviceCode">设备编号</Select.Option>,
  <Select.Option key="discoveryIP" value="discoveryIP">发现ip</Select.Option>,
  <Select.Option key="firstClass" value="firstClass">一级专业分类</Select.Option>,
  <Select.Option key="firstSecurityArea" value="firstSecurityArea">一级安全域</Select.Option>,
  <Select.Option key="haRole" value="haRole">主备地位</Select.Option>,
  <Select.Option key="isCenter" value="isCenter">总分行标识</Select.Option>,
  <Select.Option key="model" value="model">型号</Select.Option>,
  <Select.Option key="onlineStatus" value="onlineStatus">在线状态</Select.Option>,
  <Select.Option key="relatedIndicatorStatus" value="relatedIndicatorStatus">关联指标实例状态</Select.Option>,
  <Select.Option key="relatedPolicyStatus" value="relatedPolicyStatus">关联策略实例状态</Select.Option>,
  <Select.Option key="room" value="room">机房</Select.Option>,
  <Select.Option key="secondClass" value="secondClass">二级专业分类</Select.Option>,
  <Select.Option key="secondSecurityArea" value="secondSecurityArea">二级安全域</Select.Option>,
  <Select.Option key="serialNum" value="serialNum">序列号</Select.Option>,
  <Select.Option key="serverName" value="serverName">主机名</Select.Option>,
  <Select.Option key="softwareVersion" value="softwareVersion">系统版本</Select.Option>,
  <Select.Option key="syncStatus" value="syncStatus">同步状态</Select.Option>,
  <Select.Option key="syncTime" value="syncTime">同步时间</Select.Option>,
  <Select.Option key="thirdClass" value="thirdClass">三级专业分类</Select.Option>,
  <Select.Option key="updateHistory" value="updateHistory">更新历史</Select.Option>,
  <Select.Option key="updatedBy" value="updatedBy">最后更新者</Select.Option>,
  <Select.Option key="updatedTime" value="updatedTime">最后更新时间</Select.Option>,
  <Select.Option key="uuid" value="uuid">uuid</Select.Option>,
  <Select.Option key="vendor" value="vendor">厂商 </Select.Option>,

	]
