import Fenhang from './fenhang'
import ProtocolStatusInfos from './ResourceInfo/ProtocolStatusInfo'
import IntfTypeInfos from './ResourceInfo/IntfTypeInfo'
let Fenhangmaps = new Map()
Fenhang.forEach((obj, index) => {
	Fenhangmaps.set(obj.key, obj.value)
})
let ProtocolStatusmap = new Map()
ProtocolStatusInfos.forEach((obj, index) => {
	ProtocolStatusmap.set(obj.key, obj.value)
})
let IntfTypeInfomap = new Map()
IntfTypeInfos.forEach((obj, index) => {
	IntfTypeInfomap.set(obj.key, obj.value)
})
export default  [

	{
      name: 'belongsTo',
      displayName: '所属设备',
      tpe: 'String',
	  application: 'create,update',
	  applicationType: 'object',
	  isvalidate: true,
    },
	{
      name: 'name',
      displayName: '名称',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  applicationType: 'String',
	  isvalidate: true,
  },

  {
      name: 'belongsTo.onlineStatus',
      displayName: '父设备在线状态',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
	  isvalidate: true,
    },
    {
      name: 'belongsTo.managedStatus',
      displayName: '父设备纳管状态',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
	  isvalidate: true,
    },
    {
      name: 'belongsTo.appName',
      displayName: '父设备所属应用名称',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
	  isvalidate: true,
    },
    {
      name: 'portName',
      displayName: '端口名称',
      tpe: 'String',
	  application: 'show,update,filter，query',
	  applicationType: 'String',
	  isdisabled: true,
    },
    {
      name: 'discoveryIP',
      displayName: '发现 IP',
      tpe: 'String',
	  application: 'show,filter,query',
	  applicationType: 'String',
	  isvalidate: false,

    },
    {
      name: 'protocolStatus',
      displayName: '端口协议状态',
      tpe: 'String',
	  application: 'show,update,filter，query',
	  applicationType: 'select',
	  isvalidate: false,
	  isdisabled: true,
	  mappedInfos: ProtocolStatusmap,
	  options: ProtocolStatusInfos,
    },
    {
      name: 'status',
      displayName: '端口状态',
      tpe: 'String',
	  application: 'show,update,filter，query',
	  applicationType: 'select',
	  isvalidate: false,
	  isdisabled: true,
	  mappedInfos: ProtocolStatusmap,
	  options: ProtocolStatusInfos,
    },
    {
      name: 'location',
      displayName: '区域',
      tpe: 'String',
	  application: 'show,create,update,filter',
	  applicationType: 'String',
	  isvalidate: false,
    }, {
      name: 'relatedPolicyInstances',
      displayName: '关联策略总数',
      tpe: 'Integer',
	  paramsType: 'ALL',
	  application: 'show',

    }, {
      name: 'issuedPolicyInstances',
      displayName: '已下发策略数',
      tpe: 'Integer',
	  paramsType: 'ISSUED',
	  application: 'show',
    }, {
      name: 'unissuedPolicyInstances',
      displayName: '未下发策略数',
      tpe: 'Integer',
	  paramsType: 'UNISSUED',
	  application: 'show',
    }, {
      name: 'issueFailedPolicyInstances',
      displayName: '下发失败策略数',
      tpe: 'Integer',
	  paramsType: 'ISSUE_FAILED',
	  application: 'show',
    }, {
      name: 'notStdPolicyInstances',
      displayName: '非标准策略数',
      tpe: 'Integer',
	  paramsType: 'NOT_STD',
	  application: 'show',
    },
	{
      name: 'branchName',
      displayName: '所属行名称',
      tpe: 'String',
	  application: 'show,filter,query',
	  isvalidate: true,
	  applicationType: 'select',
	  mappedInfos: Fenhangmaps,
      options: Fenhang,
    },
	{
      name: 'bandwidth',
      displayName: '采集带宽',
      tpe: 'String',
	  application: 'show,update,filter,query',
	  applicationType: 'String',
	  isdisabled: true,
    },
	{
      name: 'realBandwidth',
      displayName: '实际带宽',
      tpe: 'String',
	  application: 'show,create,update,filter',
	  applicationType: 'String',
	  isvalidate: false,
    },
    {
      name: 'duplex',
      displayName: '双工类型',
      tpe: 'String',
	  application: 'show,create,update,filter',
	  applicationType: 'select',
	  options: [{ key: 'FULL', value: 'FULL' }, { key: 'HALF', value: 'HALF' }, { key: 'OTHER', value: 'OTHER' }],
	  isvalidate: false,
    },
    {
      name: 'intfLogicType',
      displayName: '物理逻辑类型',
      tpe: 'String',
	  application: 'show,create,update,filter',
	  applicationType: 'select',
	  options: [{ key: 'PHY', value: 'PHY' }, { key: 'VLAN', value: 'VLAN' }, { key: 'OTHER', value: 'OTHER' }],
	  isvalidate: false,
    },
    {
      name: 'intfType',
      displayName: '类型',
      tpe: 'String',
	  application: 'show,update,filter',
	  applicationType: 'select',
	  mappedInfos: IntfTypeInfomap,
	  options: IntfTypeInfos,
	  isvalidate: false,
	  isdisabled: true,
    },
    {
      name: 'ip',
      displayName: 'IP',
      tpe: 'String',
	  application: 'show,create,update,filter',
	  applicationType: 'String',
	  isvalidate: false,
    },
    {
      name: 'snmpIndex',
      displayName: '接口索引',
      tpe: 'int',
	  application: 'show,update,filter',
	  applicationType: 'int',
	  isvalidate: false,
	  isdisabled: true,
    },
	{
      name: 'firstClass',
      displayName: '一级专业分类',
      tpe: 'String',
	  application: 'show',
    }, {
      name: 'secondClass',
      displayName: '二级专业分类',
      tpe: 'String',
	  application: 'show',
    }, {
      name: 'thirdClass',
      displayName: '三级专业分类',
      tpe: 'String',
	  application: 'show',
    },
    {
      name: 'activatedBy',
      displayName: '激活者',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
    },


    {
      name: 'code',
      displayName: '对象编码',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
    },
    {
      name: 'createMethod',
      displayName: '创建方式',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  //applicationType:'String',
	  isvalidate: false,
	  applicationType: 'select',
	  options: [{ key: '手工', value: '手工' }, { key: '自动', value: '自动' }],
    },
	{
      name: 'onlineStatus',
      displayName: '在线状态',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  //applicationType:'String',
	  isvalidate: false,
	  applicationType: 'select',
	  options: [{ key: '新购待用', value: '新购待用' }, { key: '备件', value: '备件' }, { key: '在线', value: '在线' }, { key: '下线', value: '下线' }],
    },
    {
      name: 'managedStatus',
      displayName: '纳管状态',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  //applicationType:'String',
	  applicationType: 'select',
	  options: [{ key: '纳管', value: '纳管' }, { key: '未纳管', value: '未纳管' }],
    },
    {
      name: 'createdBy',
      displayName: '创建者',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
    },
    {
      name: 'createdTime',
      displayName: '创建时间',
      tpe: 'long',
	  application: 'show,filter,query',
	  applicationType: 'date',
    },
    {
      name: 'deactivatedBy',
      displayName: '去激活者',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
    },
    {
      name: 'deleteTime',
      displayName: '删除时间',
      tpe: 'long',
	  application: 'show,filter,query',
	  applicationType: 'date',
    },
    {
      name: 'deletedBy',
      displayName: '删除者',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
    },
    {
      name: 'description',
      displayName: '描述',
      tpe: 'String',
	  application: 'show,update,filter',
	  applicationType: 'String',
	  isvalidate: false,
	  isdisabled: true,
    },
    {
      name: 'belongsTo.firstSecArea',
      displayName: '一级安全域',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
	  isvalidate: false,
    },
	{
      name: 'belongsTo.secondSecArea',
      displayName: '二级安全域',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
	  isvalidate: false,
    },
    {
      name: 'haCollectTime',
      displayName: 'HA 状态采集时间',
      tpe: 'long',
	  application: 'show,filter',
	  applicationType: 'date',
    },
    {
      name: 'haMode',
      displayName: '主备模式',
      tpe: 'String',
	  application: 'show,create,update,filter',
	  applicationType: 'String',
	  isvalidate: false,
    },
    {
      name: 'haRole',
      displayName: '主备地位',
      tpe: 'boolean',
	  application: 'show,create,update,filter',
	  applicationType: 'select',
	  options: [{ key: 'true', value: '是' }, { key: 'false', value: '否' }],
	  isvalidate: false,
    },
    {
      name: 'keyword',
      displayName: '对象关键字',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
    },
    {
      name: 'mngtOrg',
      displayName: '设备管理机构',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
	  isvalidate: false,
    },
    {
      name: 'mngtOrgCode',
      displayName: '设备管理机构编码',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
	  isvalidate: false,
    },
    {
      name: 'monitorStatus',
      displayName: '监控状态',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
    },

    {
      name: 'branchNameCn',
      displayName: '设备所属机构',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
	  isvalidate: false,
    },
    {
      name: 'branchName',
      displayName: '设备所属机构编码',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
	  isvalidate: false,
    }, {
      name: 'appName',
      displayName: '所属应用分类名称',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
	  isvalidate: false,
    },
    {
      name: 'appCode',
      displayName: '所属应用分类编码',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
	  isvalidate: false,
    },
    {
      name: 'syncStatus',
      displayName: '同步状态',
      tpe: 'String',
	  application: 'show,create,update,filter',
	  applicationType: 'String',
	  isvalidate: false,
    },
    {
      name: 'syncTime',
      displayName: '同步时间',
      tpe: 'long',
	  application: 'show,filter',
	  applicationType: 'date',
    }, {
      name: 'updateHistory',
      displayName: '更新历史',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
    },
    {
      name: 'updatedBy',
      displayName: '最后更新者',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
    },
    {
      name: 'updatedTime',
      displayName: '最后更新时间',
      tpe: 'long',
	  application: 'show,filter',
	  applicationType: 'date',
    },
    {
      name: 'usage',
      displayName: '资源用途',
      tpe: 'String',
	  application: 'show,create,update,filter',
	  applicationType: 'String',
	  isvalidate: false,
    },
	{
	  name: 'createdByTool',
      displayName: '监控工具URL',
      tpe: 'String',
	  application: 'show,create,update,filter',
	  applicationType: 'String',
	  isvalidate: true,
	}, {
      name: 'belongsTo.objectID',
      displayName: 'ObjectID',
      tpe: 'String',
	  application: 'show,create,update,filter',
	  applicationType: 'String',
	  isvalidate: true,
    },
    {
      name: 'belongsTo.model',
      displayName: '设备类型',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  applicationType: 'String',
	  isvalidate: true,
    },
	{
		name: 'contact',
      	displayName: '联系人',
      	tpe: 'String',
	 	application: 'show',
	}, {
	  name: 'mac',
      displayName: 'MAC 地址',
      tpe: 'String',
	  application: 'update,filter',
	  applicationType: 'String',
	  isdisabled: true,
	}, {
	  name: 'mtu',
      displayName: 'MTU',
      tpe: 'String',
	  application: 'update,filter',
	  applicationType: 'String',
	  isdisabled: true,
	}, {
	  name: 'iisreset',
	  displayName: '性能监控',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  applicationType: 'String',
	  isdisabled: true,
	},
	{
	  name: 'performanceCollect',
	  displayName: '性能采集',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  applicationType: 'String',
	  isdisabled: true,
	},
	{
	  name: 'syslogMonitoring',
	  displayName: 'SYSLOG监控',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  applicationType: 'String',
	  isdisabled: true,
	},
  {
    name: 'USERNAME',
    displayName: '用户名',
    tpe: 'String',
  application: 'show,create,update,filter,query',
  applicationType: 'String',
  isvalidate: true,
  }, 
]
