import {genFilterDictOptsByName} from "../../utils/FunctionTool"
import Fenhang from './fenhang'
let Fenhangmaps = new Map()
Fenhang.forEach((obj, index) => {
	Fenhangmaps.set(obj.key, obj.value)
})
export default  [
	{
		name: 'name', //字段
      	displayName: '名称', //字段名称
      	tpe: 'String', //字段类型
	  	application: 'show,create,update,filter,query', //字段应用的场景
	 	applicationType: 'String', //create、update类型
	  	isvalidate: true,								//验证字段是否必须输入
	},
	/*{
		name: "alias",
     	displayName: "别名",
      	tpe: "String",
	  	application: "show,create,update,filter",
	  	applicationType:'String',
	},*/{
		name: 'lineType',
		displayName: '线路类型',
      	tpe: 'String',
	  	application: 'show,create,update,filter,query',
	  	applicationType: 'select',
	  	// options: [{ key: 'INTERNAL', value: '行内线路' }, { key: 'EXTERNAL', value: '第三方线路' }],
		  options:  genFilterDictOptsByName("lineType","string")
	},
	{
		name: 'typ',
		displayName: '线路分类',
      	tpe: 'String',
	  	application: 'show,create,update,filter,query',
	  	applicationType: 'select',
		options:  genFilterDictOptsByName("Line_stle","string"),
	},
	{
      name: 'branchName',
      displayName: '所属行名称',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  //applicationType:'String',
	  isvalidate: true,
	  applicationType: 'select',
      mappedInfos: Fenhangmaps,
	  options: Fenhang,
    }, {
      name: 'relatedPolicyInstances',
      displayName: '关联策略总数',
      tpe: 'Integer',
	  paramsType: 'ALL', //策略统计信息详情，查询需要的参数信息
	  application: 'show',

    }, {
      name: 'issuedPolicyInstances',
      displayName: '已下发策略数',
      tpe: 'Integer',
	  paramsType: 'ISSUED',
	  application: '',
    }, {
      name: 'unissuedPolicyInstances',
      displayName: '未下发策略数',
      tpe: 'Integer',
	  paramsType: 'UNISSUED',
	  application: '',
    }, {
      name: 'issueFailedPolicyInstances',
      displayName: '下发失败策略数',
      tpe: 'Integer',
	  paramsType: 'ISSUE_FAILED',
	  application: '',
    }, {
      name: 'notStdPolicyInstances',
      displayName: '非标准策略数',
      tpe: 'Integer',
	  paramsType: 'NOT_STD',
	  application: '',
    },

	{
		name: 'aaIntf',
     	displayName: '本端接口',
      	tpe: 'String',
	  	application: 'create,update',
	  	applicationType: 'String',
	},
	{
		name: 'aaPort',
		displayName: '本端端口',
      	tpe: 'String',
	  	application: 'create,update,filter,query',
	  	applicationType: 'String',
	},
	{
		name: 'aaDeviceIP',
		displayName: '本端设备IP',
      	tpe: 'String',
	  	application: 'show,create,update,filter,query',
	  	applicationType: 'String',
	},
	{
		name: 'aaIP',
		displayName: '本端端口IP',
      	tpe: 'String',
	  	application: 'create,update,filter',
	  	applicationType: 'String',
	  	isvalidate: true,
	},
	{
		name: 'zzIntf',
		displayName: '对端接口',
      	tpe: 'String',
	  	application: 'create,update',
	  	applicationType: 'object',
	},
	{
		name: 'zzPort',
		displayName: '对端端口',
      	tpe: 'String',
	  	application: 'create,update,filter,query',
	  	applicationType: 'String',
	},
	{
		name: 'zzDeviceIP',
		displayName: '对端设备IP',
      	tpe: 'String',
	  	application: 'create,update,filter,query',
	  	applicationType: 'String',
	},
	{
		name: 'zzIP',
		displayName: '对端端口IP',
      	tpe: 'String',
	  	application: 'show,create,update,filter',
	  	applicationType: 'String',
	},
	{
		name: 'bwFromA',
		displayName: '采集带宽来源',
      	tpe: 'boolean',
	  	application: 'create,update,filter',
	  	applicationType: 'select',
	  	options: [{ key: 'true', value: '本端' }, { key: 'false', value: '对端' }],
	},
	{
		name: 'bandwidth',
		displayName: '采集带宽',
      	tpe: 'String',
	  	application: 'create,update,filter',
	  	applicationType: 'String',
	},
	{
		name: 'realBandwidth',
		displayName: '实际带宽',
      	tpe: 'String',
	  	application: 'create,update,filter',
	  	applicationType: 'String',
	},
	{
		name: 'haMode',
		displayName: '主备模式',
      	tpe: 'String',
	  	application: 'create,update,filter',
	  	applicationType: 'String',
	},
	{
		name: 'haRole',
		displayName: '主备地位',
      	tpe: 'boolean',
	  	application: 'create,update,filter',
	  	applicationType: 'select',
	  	options: [{ key: 'true', value: '主设备' }, { key: 'false', value: '备设备' }],
	},
	{
      name: 'createMethod',
      displayName: '创建方式',
      tpe: 'String',
	  application: 'create,update,filter,query',
	  //applicationType:'String',
	  applicationType: 'select',
	  options: [{ key: '手工', value: '手工' }, { key: '自动', value: '自动' }],
    },
	{
      name: 'mngtOrg',
      displayName: '设备管理机构',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
    },
    {
      name: 'mngtOrgCode',
      displayName: '设备管理机构编码',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
    },
	{
      name: 'onlineStatus',
      displayName: '在线状态',
      tpe: 'String',
	  application: 'create,update,filter,query',
	  //applicationType:'String',
	  applicationType: 'select',
	  options: [{ key: '新购待用', value: '新购待用' }, { key: '备件', value: '备件' }, { key: '在线', value: '在线' }, { key: '下线', value: '下线' }],
    },
    {
      name: 'managedStatus',
      displayName: '纳管状态',
      tpe: 'String',
	  application: 'create,update,filter,query',
	  //applicationType:'String',
	  applicationType: 'select',
	  options: [{ key: '纳管', value: '纳管' }, { key: '未纳管', value: '未纳管' }],
    },
    {
      name: 'deviceType',
      displayName: '设备类型',
      tpe: 'String',
	  application: 'create,update,filter，query',
	  applicationType: 'String',
    },
    {
      name: 'branchNameCn',
      displayName: '设备所属机构',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
    },
    {
      name: 'branchName',
      displayName: '设备所属机构编码',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
    },
    {
      name: 'appCode',
      displayName: '所属应用分类编码',
      tpe: 'String',
	  application: 'update,create,filter',
	  applicationType: 'String',
    }, {
      name: 'appName',
      displayName: '所属应用分类名称',
      tpe: 'String',
	  application: 'update,create,filter',
	  applicationType: 'String',
    },
	{
      name: 'usage',
      displayName: '资源用途',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
    },
    {
		name: 'keyword',
		displayName: '对象关键字',
      	tpe: 'String',
	  	application: 'filter',
	  	applicationType: 'String',
	},
	{
      name: 'createdTime',
      displayName: '创建时间',
      tpe: 'long',
	  application: 'filter,query',
	  applicationType: 'date',
    }, {
      name: 'deactivatedBy',
      displayName: '去激活者',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    }, {
      name: 'deleteTime',
      displayName: '删除时间',
      tpe: 'long',
	  application: 'filter,query',
	  applicationType: 'date',
    }, {
      name: 'deletedBy',
      displayName: '删除者',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
	{
	  name: 'createdByTool',
      displayName: '监控工具URL',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
	  isvalidate: true,
	}, {
      name: 'objectID',
      displayName: 'ObjectID',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
    }, {
		name: 'srcType',
      	displayName: 'srcType',
      	tpe: 'String',
	 	application: 'update,create',
	},
    {
		name: 'lineID',
      	displayName: 'lineID',
      	tpe: 'String',
	 	application: 'update,create',
	},
	{
		name: 'provider',
      	displayName: 'provider',
      	tpe: 'String',
	 	application: 'update,create',
	},
	{
		name: 'contact',
      	displayName: '联系人',
      	tpe: 'String',
	 	application: 'update,create',
	},
	{
		name: 'USERNAME',
		displayName: '用户名',
		tpe: 'String',
	  application: 'show,create,update,filter,query',
	  applicationType: 'String',
	  isvalidate: true,
	  }, 
]
