import Fenhang from './fenhang'
let Fenhangmaps = new Map()
Fenhang.forEach((obj, index) => {
	Fenhangmaps.set(obj.key, obj.value)
})
export default [
	{
      name: 'name', //字段
      displayName: '名称', //字段名称
      tpe: 'String', //字段类型
	  application: 'show,create,update,query,filter', //字段应用的场景
	  applicationType: 'String',
	  isvalidate: true,
    }, /*{
      name: "alias",
      displayName: "别名",
      tpe: "String",
	  application: "show,update,create,query,filter",
	  applicationType:'String',
    },*/{
      name: 'hostname',
      displayName: '主机名',
      tpe: 'String',
	  application: 'show,create,update,query',
	  applicationType: 'String',
	  isvalidate: false,
    }, {
      name: 'issueFailedPolicyInstances',
      displayName: '下发失败的策略实例数量',
      tpe: 'String',
	  application: 'show',
   }, {
      name: 'issuedPolicyInstances',
      displayName: '已下发的策略实例数量 ',
      tpe: 'String',
	  application: 'show',
   }, {
      name: 'notStdPolicyInstances',
      displayName: '非标准的策略实例数量 ',
      tpe: 'String',
	  application: 'show',
   }, {
      name: 'relatedPolicyInstances',
      displayName: '总关联策略实例数量 ',
      tpe: 'String',
	  application: 'show',
   }, {
      name: 'unissuedPolicyInstances',
      displayName: '未下发的策略实例数量 ',
      tpe: 'String',
	  application: 'show',
   }, 
  //  {
  //     name: 'branchName',
  //     displayName: '所属行名称',
  //     tpe: 'String',
	//   application: 'show,update,create,filter,query',
	//   //applicationType:'String',
	//   applicationType: 'select',
  //     mappedInfos: Fenhangmaps,
	//   options: Fenhang,
  //   },
     {
      name: 'code',
      displayName: '对象编码',
      tpe: 'String',
	  application: 'show,update,create',
	  applicationType: 'String',
    }, {
      name: 'discoveryIP',
      displayName: '管理 IP',
      tpe: 'String',
	  application: 'show,update,create,filter,query',
	  applicationType: 'String',
	  isvalidate: true,
    }, {
      name: 'createMethod',
      displayName: '创建方式',
      tpe: 'String',
	  application: 'show,update,create,query',
	  //applicationType:'String',
	  applicationType: 'select',
	  options: [{ key: '手工', value: '手工' }, { key: '自动', value: '自动' }],
    }, {
      name: 'firstClass',
      displayName: '一级专业分类',
      tpe: 'String',
	  application: 'show',
    }, {
      name: 'secondClass',
      displayName: '二级专业分类',
      tpe: 'String',
	  application: 'show',
    }, {
      name: 'thirdClass',
      displayName: '三级专业分类',
      tpe: 'String',
	  application: 'show',
    }, {
      name: 'firstSecArea',
      displayName: '一级安全域',
      tpe: 'String',
	  application: 'show,update,create,filter',
	  applicationType: 'String',
    }, {
      name: 'secondSecArea',
      displayName: '二级安全域',
      tpe: 'String',
	  application: 'show,update,create,filter',
	  applicationType: 'String',
    }, {
      name: 'keyword',
      displayName: '对象关键字',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
    }, {
      name: 'location',
      displayName: '区域',
      tpe: 'String',
	  application: 'show,update,create',
	  applicationType: 'String',
    }, {
      name: 'mngtOrg',
      displayName: '设备管理机构',
      tpe: 'String',
	  application: 'show,update,create,filter',
	  applicationType: 'String',
    }, {
      name: 'mngtOrgCode',
      displayName: '设备管理机构编码',
      tpe: 'String',
	  application: 'show,update,create',
	  applicationType: 'String',
    }, {
      name: 'monitorStatus',
      displayName: '监控状态',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
    }, {
      name: 'onlineStatus',
      displayName: '在线状态',
      tpe: 'String',
	  application: 'show,update,create,filter,query',
	  //applicationType:'String',
	  applicationType: 'select',
	  options: [{ key: '新购待用', value: '新购待用' }, { key: '备件', value: '备件' }, { key: '在线', value: '在线' }, { key: '下线', value: '下线' }],
    }, {
      name: 'managedStatus',
      displayName: '纳管状态',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  //applicationType:'String',
	  applicationType: 'select',
	  options: [{ key: '纳管', value: '纳管' }, { key: '未纳管', value: '未纳管' }],
    }, {
      name: 'branchNameCn',
      displayName: '设备所属机构',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
    }, {
      name: 'branchName',
      displayName: '设备所属机构编码',
      tpe: 'String',
    application: 'show,update,create,filter,query',
	  //applicationType:'String',
	  applicationType: 'select',
	  mappedInfos: Fenhangmaps,
	  options: Fenhang,
    }, 
    {
      name: 'appCode',
      displayName: '所属应用分类编码',
      tpe: 'String',
	  application: 'show,update,create',
	  applicationType: 'String',
    }, {
      name: 'appName',
      displayName: '所属应用分类名称',
      tpe: 'String',
	  application: 'show,update,create,filter',
	  applicationType: 'String',
    }, {
      name: 'syncStatus',
      displayName: '同步状态',
      tpe: 'String',
	  application: 'show',
	  applicationType: 'String',
    }, {
      name: 'syncTime',
      displayName: '同步时间',
      tpe: 'long',
	  application: 'show',
	  applicationType: 'date',
    }, {
      name: 'createdBy',
      displayName: '创建者',
      tpe: 'String',
	  application: 'show',
	  applicationType: 'String',
    }, {
      name: 'createdTime',
      displayName: '创建时间',
      tpe: 'long',
	  application: 'show,query',
	  applicationType: 'date',
    }, {
      name: 'deactivatedBy',
      displayName: '去激活者',
      tpe: 'String',
	  application: 'show,filter',
	  applicationType: 'String',
    }, {
      name: 'deleteTime',
      displayName: '删除时间',
      tpe: 'long',
	  application: 'show,query',
	  applicationType: 'date',
    }, {
      name: 'deletedBy',
      displayName: '删除者',
      tpe: 'String',
	  application: 'show',
	  applicationType: 'String',
    }, {
      name: 'description',
      displayName: '描述',
      tpe: 'String',
	  application: 'show,update,create',
	  applicationType: 'String',
    }, {
      name: 'updateHistory',
      displayName: '更新历史',
      tpe: 'String',
	  application: 'show',
	  applicationType: 'String',
    }, {
      name: 'updatedBy',
      displayName: '最后更新者',
      tpe: 'String',
	  application: 'show',
	  applicationType: 'String',
    }, {
      name: 'updatedTime',
      displayName: '最后更新时间',
      tpe: 'long',
	  application: 'show',
	  applicationType: 'date',
    }, {
      name: 'usage',
      displayName: '资源用途',
      tpe: 'String',
	  application: 'show',
	  applicationType: 'String',
    }, {
      name: 'activatedBy',
      displayName: '激活者',
      tpe: 'String',
	  application: 'show',
	  applicationType: 'String',
    }, {
      name: 'snmpVer',
      displayName: 'SNMP 版本',
      tpe: 'String',
	  application: 'show,update,create',
	  applicationType: 'select',
	  options: [{ key: 'V1', value: 'V1' }, { key: 'V2', value: 'V2' }, { key: 'V3', value: 'V3' }, { key: 'OTHER', value: 'OTHER' }],
    }, {
      name: 'snmpCommunity',
      displayName: 'SNMP 团体串',
      tpe: 'String',
	  application: 'show,update,create',
    }, {
	  name: 'createdByTool',
      displayName: '监控工具URL',
      tpe: 'String',
	  application: 'show,update,create',
	  applicationType: 'String',
	  isvalidate: true,
	}, {
		name: 'srcType',
      	displayName: 'srcType',
      	tpe: 'String',
	 	application: 'show,update,create',
	},
	{
		name: 'contact',
      	displayName: '联系人',
      	tpe: 'String',
	 	application: 'show,update,create',
  },
/*   {
    name: 'secondClass',
    displayName: '类型',
    tpe: 'String',
    application: 'show,update,create,filter',  
    applicationType: 'select',
    options: [{ key: 'MW_WEBLOGIC', value: 'Weblogic' }, { key: 'MW_WEBSPHERE', value: 'Websphere' }, { key: 'MW_TOMCAT', value: 'Tomcat' }, { key: 'MW_KAFKA', value: 'Kafka' }],
  }, */
  {
    name: 'room',
    displayName: '机房',
    tpe: 'String',
    application: 'show,update,create,filter',  
    applicationType: 'String',
  },
  {
    name: 'version',
    displayName: '版本',
    tpe: 'String',
    application: 'show,update,create,filter',  
    applicationType: 'String',
  },
  {
    name: 'port',
    displayName: '端口',
    tpe: 'String',
    application: 'show,update,create,filter',  
    applicationType: 'String',
  },
  {
    name: 'instance',
    displayName: '实例名',
    tpe: 'String',
    application: 'show,update,create,filter',  
    applicationType: 'String',
  },
  {
    name: 'USERNAME',
    displayName: '用户名',
    tpe: 'String',
  application: 'show,create,update,filter,query',
  applicationType: 'String',
  isvalidate: true,
  }, 
]
