import Fenhang from './fenhang'
import { firstSecurityZone } from '../../utils/SecurityZone'
let Fenhangmaps = new Map()
Fenhang.forEach((obj, index) => {
	Fenhangmaps.set(obj.key, obj.value)
})
export default  [

	{
      name: 'name',
      displayName: '名称',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  applicationType: 'String',
	  isvalidate: true,
    }, {
      name: 'discoveryIP',
      displayName: '管理IP',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  applicationType: 'String',
	  isvalidate: true,
    }, {
      name: 'branchName',
      displayName: '所属行名称',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  //applicationType:'String',
	  isvalidate: true,
	  applicationType: 'select',
	  mappedInfos: Fenhangmaps,
	  options: Fenhang,
    },
    {
      name: 'mngInfoSrc',
      displayName: '发现方式',
      tpe: 'String',
		  application: 'show,create,update,filter,query',
		  isvalidate: false,
		  applicationType: 'select',
		  isOnchange: true,
		  options: [{ key: '手工', value: '手工' }, { key: '自动', value: '自动' }],
		  isvalidate: true,
		  defaultValue: '手工',
    },
    {
      name: 'hostname',
      displayName: '主机名',
      tpe: 'String',
	  application: 'create,update,filter,query',
	  applicationType: 'String',
	  isvalidate: false,
	  isdisabled: true,
    }, {
      name: 'objectID',
      displayName: 'ObjectID',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
	  isdisabled: true,
    }, 
    {
      name: 'activatedBy',
      displayName: '激活者',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
	  name: 'createdByTool',
      displayName: '监控工具URL',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
	  isdisabled: true,
	},
    {
      name: 'haMode',
      displayName: '主备模式',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'haRole',
      displayName: '主备地位',
      tpe: 'boolean',
	  application: 'filter',
	  applicationType: 'select',
	  options: [{ key: 'true', value: '主设备' }, { key: 'false', value: '备设备' }],

    },
    {
      name: 'keyword',
      displayName: '对象关键字',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'mngtOrg',
      displayName: '设备管理机构',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'select',
	  options: Fenhang,
    },
    {
      name: 'mngtOrgCode',
      displayName: '设备管理机构编码',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'onlineStatus',
      displayName: '在线状态',
      tpe: 'String',
	  application: 'create,update,filter,query',
	  //applicationType:'String',
	  applicationType: 'select',
	  options: [{ key: '在线', value: '在线' }, { key: '待上线', value: '待上线' }, { key: '已下线', value: '已下线' }],
//	  options:[{key: '新购待用', value: '新购待用'},{key: '备件', value: '备件'},{key: '在线', value: '在线'}, {key: '下线', value: '下线'}],
    },
    {
      name: 'managedStatus',
      displayName: '纳管状态',
      tpe: 'String',
	  application: 'create,update,filter,query',
	  //applicationType:'String',
	  applicationType: 'select',
	  options: [{ key: '纳管', value: '纳管' }, { key: '未纳管', value: '未纳管' }],
    },
    {
      name: 'deviceType',
      displayName: '设备类型',
      tpe: 'String',
	  application: 'filter，query',
	  applicationType: 'String',
    },
    {
      name: 'branchNameCn',
      displayName: '设备所属机构',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'branchName',
      displayName: '设备所属机构编码',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
	{
      name: 'appCode',
      displayName: '所属应用分类编码',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'appName',
      displayName: '所属应用分类名称',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'usage',
      displayName: '资源用途',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'softwareVersion',
      displayName: '系统版本',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
    },
    {
      name: 'typ',
      displayName: '类型',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
    },
    {
      name: 'createdBy',
      displayName: '创建者',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'createdTime',
      displayName: '创建时间',
      tpe: 'long',
	  application: 'filter,query',
	  applicationType: 'date',
    },
    {
      name: 'deactivatedBy',
      displayName: '去激活者',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'deleteTime',
      displayName: '删除时间',
      tpe: 'long',
	  application: 'filter,query',
	  applicationType: 'date',
    },
    {
      name: 'deletedBy',
      displayName: '删除者',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
	{
      name: 'updatedBy',
      displayName: '最后更新者',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'updatedTime',
      displayName: '最后更新时间',
      tpe: 'long',
	  application: 'filter',
	  applicationType: 'date',
    },
    {
      name: 'USERNAME',
      displayName: '用户名',
      tpe: 'String',
    application: 'show,create,update,filter,query',
    applicationType: 'String',
    isvalidate: true,
    }, 
]
