//name: "name",                  				//字段
//displayName: "名称",           				//字段名称
//tpe: "String",                 				//show应用字段类型,（String,int,long）
//application: "show,create,update,filter",  	//字段应用的场景（show,create,update,filter,query）
//applicationType:'String',  //create,update,filter,query应用才需要此类型包括(String,date,select,int,long,Integer)
//isdisabled：                          //create、update禁止填写的字段内容true、false（如果禁止，isvalidate is false）
//isvalidate:true,			 //验证字段是否必须输入
//paramsType:"ALL",          //策略统计信息详情，查询需要的参数信息（ALL,ISSUED,UNISSUED,ISSUE_FAILED,NOT_STD）
//mappedInfos:               //在list展示时，需要的映射
import Fenhang from './fenhang'
import { firstSecurityZone } from '../../utils/SecurityZone'
import { getSourceByKey } from "../../utils/FunctionTool"
let Fenhangmaps = new Map()
Fenhang.forEach((obj, index) => {
	Fenhangmaps.set(obj.key, obj.value)
})

export default  [
	{
      name: 'name',
      displayName: '名称',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  applicationType: 'String',
	  isvalidate: true,
    }, {
      name: 'discoveryIP',
      displayName: '设备IP',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  applicationType: 'String',
	  isvalidate: true,
    }, {
      name: 'branchName',
      displayName: '所属行名称',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  //applicationType:'String',
	  isvalidate: true,
	  applicationType: 'select',
	  mappedInfos: Fenhangmaps,
	  options: Fenhang,
    },
    {
      name: 'firstSecArea',
      displayName: '一级安全域',
      tpe: 'String',
	  application: 'show,create,update,filter',
	  applicationType: 'select',
	  options: firstSecurityZone, //[{key: '分行生产区', value: '分行生产区'},{key: '分行办公区', value: '分行办公区'},{key: '分行中间业务区', value: '分行中间业务区'},{key: '分行下联区', value: '分行下联区'},{key: '分行上联区', value: '分行上联区'},{key: '分行核心交换区', value: '分行核心交换区'},{key: '分行视频接入区', value: '分行视频接入区'},{key: '二级分行', value: '二级分行'},{key: '支行', value: '支行'},{key: '社区银行', value: '社区银行'},{key: '自助银行', value: '自助银行'}],
	  isvalidate: true,
    },
    {
      name: 'secondSecArea',
      displayName: '二级安全域',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'select',
    options: getSourceByKey('secondSecArea'),
    },
    {
      name: 'vendor',
      displayName: '厂商',
      tpe: 'String',
	  application: 'show,create,update,filter,query',
	  applicationType: 'select',
	  isvalidate: true,
	  options: [{ key: 'CISCO', value: 'CISCO' }, { key: 'JUNIPER', value: 'JUNIPER' }, { key: 'HW', value: 'HW' }, { key: 'H3C', value: 'H3C' }, { key: 'MP', value: 'MP' }, { key: 'ZTE', value: 'ZTE' }, { key: 'XASJ', value: 'XASJ' }, { key: 'F5', value: 'F5' }, { key: 'RUIJIE', value: 'RUIJIE' }, { key: 'OTHER', value: 'OTHER' }],
    },
    {
      name: 'snmpVer',
      displayName: 'SNMP 版本 ',
      tpe: 'String',
		  application: 'filter,create,update',
		  applicationType: 'select',
		  isvalidate: true,
		  options: [{ key: 'V1', value: 'V1' }, { key: 'V2', value: 'V2' }, { key: 'V2C', value: 'V2C' }, { key: 'V3', value: 'V3' }, { key: 'OTHER', value: 'OTHER' }],
		  defaultValue: 'V1',
    },
    {
      name: 'snmpCommunity',
      displayName: 'SNMP 团体串',
      tpe: 'String',
		  application: 'create,update',
		  applicationType: 'String',
		  isvalidate: true,
    },
    {
      name: 'snmpWriteCommunity',
      displayName: 'SNMP 写团体串',
      tpe: 'String',
	  application: 'create,update',
	  applicationType: 'String',
	  isvalidate: false,
    },
    {
      name: 'mngInfoSrc',
      displayName: '发现方式',
      tpe: 'String',
		  application: 'show,create,update,filter,query',
		  //applicationType:'String',
		  isvalidate: false,
		  applicationType: 'select',
		  isOnchange: true,
		  options: [{ key: '手工', value: '手工' }, { key: '自动', value: '自动' }],
		  isvalidate: true,
		  defaultValue: '自动',
    },
    {
      name: 'hostname',
      displayName: '主机名',
      tpe: 'String',
	  application: 'create,update,filter,query',
	  applicationType: 'String',
	  isvalidate: false,
	  isdisabled: true,
    }, {
      name: 'location',
      displayName: '区域',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
	  isdisabled: true,
    }, {
      name: 'objectID',
      displayName: 'ObjectID',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
	  isdisabled: true,
    }, {
      name: 'intfNum',
      displayName: '接口总数',
      tpe: 'int',
	  application: '',
	  applicationType: 'int',
    }, {
      name: 'relatedPolicyInstances',
      displayName: '关联策略总数',
      tpe: 'Integer',
	  paramsType: 'ALL', //策略统计信息详情，查询需要的参数信息
	  application: 'show',

    }, {
      name: 'issuedPolicyInstances',
      displayName: '已下发策略数',
      tpe: 'Integer',
	  paramsType: 'ISSUED',
	  application: '',
    }, {
      name: 'unissuedPolicyInstances',
      displayName: '未下发策略数',
      tpe: 'Integer',
	  paramsType: 'UNISSUED',
	  application: '',
    }, {
      name: 'issueFailedPolicyInstances',
      displayName: '下发失败策略数',
      tpe: 'Integer',
	  paramsType: 'ISSUE_FAILED',
	  application: '',
    }, {
      name: 'notStdPolicyInstances',
      displayName: '非标准策略数',
      tpe: 'Integer',
	  paramsType: 'NOT_STD',
	  application: '',
    }, {
      name: 'firstClass',
      displayName: '一级专业分类',
      tpe: 'String',
	  application: '',
    }, {
      name: 'secondClass',
      displayName: '二级专业分类',
      tpe: 'String',
	  application: '',
    }, {
      name: 'thirdClass',
      displayName: '三级专业分类',
      tpe: 'String',
	  application: '',
    },
    {
      name: 'activatedBy',
      displayName: '激活者',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
	  name: 'createdByTool',
      displayName: '监控工具URL',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
	  isdisabled: true,
	},
    {
      name: 'cabinet',
      displayName: '机柜',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'code',
      displayName: '对象编码',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'description',
      displayName: '描述',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
    },
    {
      name: 'deviceCode',
      displayName: '设备编号',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
	  isvalidate: false,
    },
    {
      name: 'haCollectTime',
      displayName: 'HA 状态采集时间',
      tpe: 'long',
	  application: 'filter',
	  applicationType: 'date',
    },
    {
      name: 'haMode',
      displayName: '主备模式',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'haRole',
      displayName: '主备地位',
      tpe: 'boolean',
	  application: 'filter',
	  applicationType: 'select',
	  options: [{ key: 'true', value: '主设备' }, { key: 'false', value: '备设备' }],

    },
    {
      name: 'keyword',
      displayName: '对象关键字',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'mngtOrg',
      displayName: '设备管理机构',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'select',
	  options: Fenhang,
    },
    {
      name: 'mngtOrgCode',
      displayName: '设备管理机构编码',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'model',
      displayName: '型号',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'String',
    },
    {
      name: 'monitorStatus',
      displayName: '监控状态',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'onlineStatus',
      displayName: '在线状态',
      tpe: 'String',
	  application: 'create,update,filter,query',
	  //applicationType:'String',
	  applicationType: 'select',
	  options: [{ key: '在线', value: '在线' }, { key: '待上线', value: '待上线' }, { key: '已下线', value: '已下线' }],
//	  options:[{key: '新购待用', value: '新购待用'},{key: '备件', value: '备件'},{key: '在线', value: '在线'}, {key: '下线', value: '下线'}],
    },
    {
      name: 'managedStatus',
      displayName: '纳管状态',
      tpe: 'String',
	  application: 'create,update,filter,query',
	  //applicationType:'String',
	  applicationType: 'select',
	  options: [{ key: '纳管', value: '纳管' }, { key: '未纳管', value: '未纳管' }],
    },
    {
      name: 'deviceType',
      displayName: '设备类型',
      tpe: 'String',
	  application: 'filter，query',
	  applicationType: 'String',
    },
    {
      name: 'branchNameCn',
      displayName: '设备所属机构',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'branchName',
      displayName: '设备所属机构编码',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'room',
      displayName: '机房',
      tpe: 'String',
	  application: 'create,update,filter',
	  applicationType: 'select',
	  options: [{ key: '上地', value: '上地' }, { key: '酒仙桥', value: '酒仙桥' }, { key: '武汉灾备', value: '武汉灾备' }],
    },
    {
      name: 'serialNum',
      displayName: '序列号',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'softwareVersion',
      displayName: '系统版本',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
	{
      name: 'appCode',
      displayName: '所属应用分类编码',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'appName',
      displayName: '所属应用分类名称',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'syncStatus',
      displayName: '同步状态',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'syncTime',
      displayName: '同步时间',
      tpe: 'long',
	  application: 'filter',
	  applicationType: 'date',
    }, {
      name: 'updateHistory',
      displayName: '更新历史',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'usage',
      displayName: '资源用途',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
   {
      name: 'createdBy',
      displayName: '创建者',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'createdTime',
      displayName: '创建时间',
      tpe: 'long',
	  application: 'filter,query',
	  applicationType: 'date',
    },
    {
      name: 'deactivatedBy',
      displayName: '去激活者',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'deleteTime',
      displayName: '删除时间',
      tpe: 'long',
	  application: 'filter,query',
	  applicationType: 'date',
    },
    {
      name: 'deletedBy',
      displayName: '删除者',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
	{
      name: 'updatedBy',
      displayName: '最后更新者',
      tpe: 'String',
	  application: 'filter',
	  applicationType: 'String',
    },
    {
      name: 'updatedTime',
      displayName: '最后更新时间',
      tpe: 'long',
	  application: 'filter',
	  applicationType: 'date',
    }, {
		name: 'srcType',
      	displayName: 'srcType',
      	tpe: 'String',
	 	application: 'create, update',
applicationType: 'select',
	  	options: [{ key: 'CISCO', value: 'CISCO' }, { key: 'MAIPU', value: 'MAIPU' }, { key: 'JUNIPER', value: 'JUNIPER' }, { key: 'H3C', value: 'H3C' }, { key: 'RUIJIE', value: 'RUIJIE' }, { key: 'CISCO-NEXUS', value: 'CISCO-NEXUS' }, { key: 'HILLSTONE', value: 'HILLSTONE' }, { key: 'SHINAIDE', value: 'SHINAIDE' }, { key: 'JUNIPER-SRX', value: 'JUNIPER-SRX' }],
	},
	{
		name: 'contact',
      	displayName: '联系人',
      	tpe: 'String',
	 	application: '',
	},
	{
		name: 'syncStatus',
      	displayName: '发现状态',
      	tpe: 'String',
	 	application: 'create, update',
	 	applicationType: 'select',
	 	options: [{ key: 'unsync', value: '尚未同步' }, { key: 'success', value: '成功' }, { key: 'failed', value: '失败' }, { key: 'syncing', value: '同步中' }],
	 	defaultValue: 'unsync',
	 	isdisabled: true,
	},
	{
		name: 'syncTime',
      	displayName: '发现时间',
      	tpe: 'long',
	 	application: 'create, update',
	 	applicationType: 'date',
	 	isdisabled: true,
	},
  {
    name: 'USERNAME',
    displayName: '用户名',
    tpe: 'String',
  application: 'show,create,update,filter,query',
  applicationType: 'String',
  isvalidate: true,
  }, 
]
