export default {
    User:[
        {
            value:'userLogin',
            name:'用户登录'
        },
        {
            value:'iamLogin',
            name:'iam登录'
        },
        {
            value:'mpoinLogin',
            name:'mpoin登录'
        },
        {
            value:'logout',
            name:'登出'
        },
        {
            value:'changePassword',
            name:'修改密码'
        },
        {
            value:'pollUsers',
            name:'同步用户信息'
        },
        {
            value:'syncUserPassword',
            name:'IAM应急密码同步'
        },
        {
            value:'update',
            name:'更新'
        },
        {
            value:'add',
            name:'新增'
        },
        {
            value:'delete',
            name:'删除'
        },
        {
            value:'batchDelete',
            name:'批量删除'
        },
    ],
    Role:[
        {
            value:'update',
            name:'更新'
        },
        {
            value:'add',
            name:'新增'
        },
        {
            value:'delete',
            name:'删除'
        },
        {
            value:'batchDelete',
            name:'批量删除'
        },

    ],
    ReporterStatus:[
        {
            value:'get',
            name:'查询'
        },
        {
            value:'exportResultToExcel',
            name:'导出'
        },
        {
            value:'batchUpdateMaintainStatus',
            name:'批量更新维护期状态'
        },
    ],
    MO:[
        {
            value:'update',
            name:'更新资源'
        },
        {
            value:'backgroundSync',
            name:'批量同步MO信息-后台专用'
        },
        {
            value:'batchSync',
            name:'批量同步MO信息'
        },
        {
            value:'batchManagedStatus',
            name:'批星修改MO纳管狀态'
        },
        {
            value:'discovery',
            name:'自服务向导设备发现'
        },
        {
            value:'discoveryOsNantian',
            name:'基于南天zabbix 发现操作系统'
        },
        {
            value:'addMonitor',
            name:'基于南天zabbix给操作系统上监控'
        },
        {
            value:'discoveryBatch',
            name:'基于南天Zabbix批量发现操作系统'
        },
        {
            value:'checkNTExists',
            name:'基于南天zabbix监测是否己存在监控'
        },
        {
            value:'addMonitorBatch',
            name:'基于离天Zabbix操作系统批量上监控'
        },
        {
            value:'offLineNantian',
            name:'基于南天自服务MO批量下线'
        },
        {
            value:'offLine',
            name:'下线'
        },
        {
            value:'change',
            name:'自服务向导设备变更'
        },
        {
            value:'discoveryDb',
            name:'获取数据库资源发现信息'
        },
        {
            value:'changeDB',
            name:'自服务向导数据库变更'
        },
        {
            value:'updateMOs',
            name:'MO 模式组子类同步'
        },
        {
            value:'discoveryOs',
            name:'获取操作系统资源发现信息'
        },
        {
            value:'changeOS',
            name:'操作系统自服务向导设备变更'
        },
        {
            value:'updateIntf',
            name:'更新接口'
        },
        {
            value:'updateFileSystem',
            name:'更新文件系统'
        },
        {
            value:'updateDisk',
            name:'更新磁盘'
        },
        {
            value:'add',
            name:'新增资源'
        },
        {
            value:'addDBInfos',
            name:'新增数据库和数据库资源信息'
        },
        {
            value:'zabbixAdd',
            name:'添加MO'
        },
        {
            value:'addIntf',
            name:'新增接口'
        },
        {
            value:'addNeAndIntfs',
            name:'新增设备和设备下的接口'
        },
        {
            value:'addFileSystem',
            name:'新增文件系统'
        },
        {
            value:'addDisk',
            name:'新增磁盘'
        },
        {
            value:'addOsAndFsAndDisk',
            name:'新增操作系统、文件系统和磁蛊'
        },
        {
            value:'delete',
            name:'删除资源'
        },
        {
            value:'batchDelete',
            name:'批量删除资源'
        },
        {
            value:'delByQ',
            name:'按条件删除MO'
        },
        {
            value:'delIntf',
            name:'删除接口'
        },
        {
            value:'delIntfs',
            name:'批量删除NE接口'
        },
        {
            value:'batchDelIntfs',
            name:'批量删除接口'
        },
        {
            value:'delFileSystem',
            name:'删除文件系统'
        },
        {
            value:'delFileSystems',
            name:'批量删除OS文件系统'
        },
        {
            value:'batchDelFileSystems',
            name:'批量刪除文件系统'
        },
        {
            value:'delDisk',
            name:'删除磁盘'
        },
        {
            value:'delDisks',
            name:'批量删除OS磁盘'
        },
        {
            value:'batchDelDisks',
            name:'批量删除磁盘'
        },
        {
            value:'importMOInfo',
            name:'导入MO信息'
        },
        {
            value:'exportMOInfo',
            name:'下载MO模板'
        },
    ],
    NotificationRule:[
        {
            value:'update',
            name:'更新'
        },
        {
            value:'add',
            name:'新增'
        },
        {
            value:'delete',
            name:'删除'
        },
        {
            value:'batchDelete',
            name:'批量删除'
        },
    ],
    Rule:[
        {
            value:'calc',
            name:'计算规则实例化夏盖情况'
        },
        {
            value:'issueSyslog',
            name:'下发Syslog策略'
        },
        {
            value:'issue',
            name:'下发'
        },
        {
            value:'issueDistributed',
            name:'分布式下发'
        },
        {
            value:'issueAPM',
            name:'APM下发'
        },
        {
            value:'update',
            name:'更新资源'
        },
        {
            value:'issueOffline',
            name:'分布式规则下线'
        },
        {
            value:'add',
            name:'新增资源'
        },
        {
            value:'delete',
            name:'删除资源'
        },
        {
            value:'batchDelete',
            name:'批量删除资源'
        }
    ],
    RuleInst:[
        {
            value:'update',
            name:'更新资源'
        },
        {
            value:'updateItemRuleInst',
            name:'更新itm监控实例'
        },
        {
            value:'updateIssueStatus',
            name:'更新监控实例下发状态'
        },
        {
            value:'add',
            name:'新增资源'
        },
        {
            value:'addItmRuleInst',
            name:'新增itm监控实例'
        },
        {
            value:'delete',
            name:'删除资源'
        },
        {
            value:'batchDelete',
            name:'批量删除资源'
        },
        {
            value:'savePreviewData',
            name:'保存预览的实例'
        },
        {
            value:'issue',
            name:'下发'
        },
        {
            value:'reissue',
            name:'清除指定条件数据并重下发'
        },
        {
            value:'issuePreviewData',
            name:'基于预览数据的下发'
        },
        {
            value:'issueAfterOffline',
            name:'基于MO下线后的下发'
        }
    ],
    EventsMenuConf:[
        {
            value:'rightClickMenu',
            name:'OEL右键菜单操作'
        },
        {
            value:'ticket',
            name:'发送工单'
        },
    ],
    Mt:[
        {
            value:'update',
            name:'更新资源'
        },
        {
            value:'disable',
            name:'禁用维护期'
        },
        {
            value:'adjust',
            name:'微调维护期'
        },
        {
            value:'review',
            name:'复核维护期'
        },
        {
            value:'updateMtHistoryData',
            name:'历史数据添加应用系统'
        },
        {
            value:'updateMtAppNameAutoAndAppNameEditing',
            name:'更新维护期应用系统'
        },
        {
            value:'updateNoticed',
            name:'批量更新维护期发送通知标记'
        },
        {
            value:'add',
            name:'新增资源'
        },
        {
            value:'delete',
            name:'删除资源'
        },
        {
            value:'batchDelete',
            name:'批量删除资源'
        },
        {
            value:'importMtInfo',
            name:'导入老系统维护期数据'
        },
        {
            value:'importMtInfoFromExcel',
            name:'导入维护期数据'
        }
    ],
    SelfService:[
        {
            value:'addMonitorBatch',
            name:'自服务上线'
        },
        {
            value:'offLineNantian',
            name:'自服务下线'
        },
    ]
}  