export default  {
	treeData: [
		{
	  	title: '监控对象',
	  	key: '1',
	  	children: [{
	  		title: '查看监控对象',
	  		key: 'checked_mo_see',
	  	}, {
	  		title: '新增监控对象',
	  		key: 'checked_mo_create',
	  	}, {
	  		title: '编辑监控对象',
	  		key: 'checked_mo_update',
	  	}, {
	  		title: '删除监控对象',
	  		key: 'checked_mo_delete',
	  	}],
	  }, {
	  	title: '策略规则',
	  	key: '2',
	  	children: [{
	  		title: '查看规则',
	  		key: 'checked_rule_see',
	  	}, {
	  		title: '新增规则',
	  		key: 'checked_rule_create',
	  	}, {
	  		title: '编辑规则',
	  		key: 'checked_rule_update',
	  	}, {
	  		title: '删除规则',
	  		key: 'checked_rule_delete',
	  	}, {
	  		title: '下发规则',
	  		key: 'checked_rule_issu',
	  	}, {
	  		title: '计算规则',
	  		key: 'checked_rule_cal',
	  	}],
	  }, {
	  	title: '策略模板',
	  	key: '3',
	  	children: [{
	  		title: '查看策略模板',
	  		key: 'checked_temp_see',
	  	}, {
	  		title: '新增策略模板',
	  		key: 'checked_temp_create',
	  	}, {
	  		title: '编辑策略模板',
	  		key: 'checked_temp_update',
	  	}, {
	  		title: '删除策略模板',
	  		key: 'checked_temp_delete',
	  	}],
	  }, {
	  	title: '监控实例',
	  	key: '4',
	  	children: [{
	  		title: '查看监控实例',
	  		key: 'checked_inst_see',
	  	}, {
	  		title: '新增监控实例',
	  		key: 'checked_inst_create',
	  	}, {
	  		title: '编辑监控实例',
	  		key: 'checked_inst_update',
	  	}, {
	  		title: '删除监控实例',
	  		key: 'checked_inst_delete',
	  	}],
	  }, {
	  	title: '告警',
	  	key: '5',
	  	children: [{
	  		title: '查看告警',
	  		key: 'checked_alarm_see',
	  	}, {
	  		title: '确认告警',
	  		key: 'checked_alarm_confirm',
	  	}, {
	  		title: '关闭告警',
	  		key: 'checked_alarm_close',
	  	}],
	  }, {
	  	title: '策略实例',
	  	key: '6',
	  	children: [{
	  		title: '查看策略实例',
	  		key: 'checked_policy_see',
	  	}, {
	  		title: '新增策略实例',
	  		key: 'checked_policy_create',
	  	}, {
	  		title: '编辑策略实例',
	  		key: 'checked_policy_update',
	  	}, {
	  		title: '删除策略实例',
	  		key: 'checked_policy_delete',
	  	}],
	  }, {
	  	title: '用户管理',
	  	key: '7',
	  	children: [{
	  		title: '查看用户',
	  		key: 'checked_user_see',
	  	}, {
	  		title: '新增用户',
	  		key: 'checked_user_create',
	  	}, {
	  		title: '编辑用户',
	  		key: 'checked_user_update',
	  	}, {
	  		title: '删除用户',
	  		key: 'checked_user_delete',
	  	}],
	  }, {
	  	title: '角色管理',
	  	key: '8',
	  	children: [{
	  		title: '查看角色',
	  		key: 'checked_role_see',
	  	}, {
	  		title: '新增角色',
	  		key: 'checked_role_create',
	  	}, {
	  		title: '编辑角色',
	  		key: 'checked_role_update',
	  	}, {
	  		title: '删除角色',
	  		key: 'checked_role_delete',
	  	}],
	  }, {
	  	title: '监控工具',
	  	key: '9',
	  	children: [{
	  		title: '查看工具',
	  		key: 'checked_tool_see',
	  	}, {
	  		title: '新增工具',
	  		key: 'checked_tool_create',
	  	}, {
	  		title: '编辑工具',
	  		key: 'checked_tool_update',
	  	}, {
	  		title: '删除工具',
	  		key: 'checked_tool_delete',
	  	}],
	  }, {
	  	title: '时间周期',
	  	key: '10',
	  	children: [{
	  		title: '查看时间周期',
	  		key: 'checked_time_see',
	  	}, {
	  		title: '新增时间周期',
	  		key: 'checked_time_create',
	  	}, {
	  		title: '编辑时间周期',
	  		key: 'checked_time_update',
	  	}, {
	  		title: '删除时间周期',
	  		key: 'checked_time_delete',
	  	}],
	  }, {
	  	title: '指标',
	  	key: '11',
	  	children: [{
	  		title: '查看指标',
	  		key: 'checked_kpi_see',
	  	}, {
	  		title: '新增指标',
	  		key: 'checked_kpi_create',
	  	}, {
	  		title: '编辑指标',
	  		key: 'checked_kpi_update',
	  	}, {
	  		title: '删除指标',
	  		key: 'checked_kpi_delete',
	  	}],
	  }, {
	  	title: '指标实现',
	  	key: '12',
	  	children: [{
	  		title: '查看指标实现',
	  		key: 'checked_zabbix_see',
	  	}, {
	  		title: '新增指标实现',
	  		key: 'checked_zabbix_create',
	  	}, {
	  		title: '编辑指标实现',
	  		key: 'checked_zabbix_update',
	  	}, {
  			title: '删除指标实现',
  			key: 'checked_zabbix_delete',
  		}],
  	}, {
	  	title: '维护期模板管理',
	  	key: '13',
	  	children: [{
	  		title: '查看模板管理',
	  		key: 'checked_mt_template_see',
	  	}, {
	  		title: '新增模板管理',
	  		key: 'checked_mt_template_create',
	  	}, {
	  		title: '编辑模板管理',
	  		key: 'checked_mt_template_update',
	  	}, {
  			title: '删除模板管理',
  			key: 'checked_mt_template_delete',
  		}],
  	}, {
	  	title: '维护期实例管理',
	  	key: '14',
	  	children: [{
	  		title: '查看实例管理',
	  		key: 'checked_mt_see',
	  	}, {
	  		title: '新增实例管理',
	  		key: 'checked_mt_create',
	  	}, {
	  		title: '编辑实例管理',
	  		key: 'checked_mt_update',
	  	}, {
  			title: '删除实例管理',
  			key: 'checked_mt_delete',
  		}, {
  			title: '创建专家模式',
  			key: 'checked_mt_expert_create',
  		}, {
  			title: '编辑专家模式',
  			key: 'checked_mt_expert_update',
  		}],
  	},
 	],
 }
