import {ozr} from './clientSetting'

export default [
  {
    id: 1,
    icon: 'home',
    name: '首页',
    router: '/dashboard',
  },
  {
    id: 2,
   	bpid: 1,
    name: '监控对象管理',
		icon: 'icon-laptop',
    router: '/router',
  },
  {
    id: 8,
    bpid: 1,
    name: '监控工具',
    icon: 'icon-tool',
  },
  {
    id: 81,
    bpid: 8,
    mpid: 8,
    name: '工具浏览',
		icon: 'icon-bars',
    router: '/toollist',
  },
  {
    id: 82,
    mpid: -1,
    bpid: 81,
    name: '配置详情',
    icon: 'file-text',
    router: '/cfglist/:id',
  }, {
    id: 1000,
    bpid: 1,
    name: '策略管理',
		icon: 'icon-cloud',
  },
  {
    id: 10001,
    bpid: 1000,
    mpid: 1000,
    name: '策略模板管理',
		icon: 'icon-policy',
    router: '/policyTempletGroup',
  },
  {
    id: 10002,
    bpid: 1000,
    mpid: 1000,
    name: '策略实例管理',
		icon: 'icon-instance',
    router: '/policyInstanceGroup',
  },
  {
    id: 10003,
    bpid: 1000,
    mpid: 1000,
    name: '策略规则管理',
		icon: 'icon-rule',
		router: '/policyRuleGroup',
  },
  {
    id: 10004,
    bpid: 1000,
    mpid: 1000,
    name: '监控实例',
		icon: 'icon-ruleinstance',
    router: '/ruleInstanceGroup',
  },
  {
    id: 10005,
    bpid: 1000,
    mpid: 1000,
    name: '指标管理',
		icon: 'icon-stdindicator',
    router: '/stdIndicatorGroup',
  },
  {
    id: 10006,
    bpid: 1000,
    mpid: 1000,
    name: '指标实现',
		icon: 'icon-zabbix',
    router: '/zabbixItemsGroup',
  },
  {
    id: 1001,
    bpid: 1,
    name: '配置',
		icon: 'icon-setting',
  },
  {
    id: 10011,
    bpid: 1001,
    mpid: 1001,
    name: '周期管理',
		icon: 'icon-time',
    router: '/timePeriods',
  },
  {
    id: 10012,
    bpid: 1001,
    mpid: 1001,
    name: '通知管理',
		icon: 'icon-api',
    router: '/notification',
  },
  {
    id: 1002,
    bpid: 1,
    name: '告警管理',
		icon: 'icon-api',
  },
  {
    id: 10022,
    bpid: 1002,
    mpid: 1002,
    name: '告警列表',
		icon: 'icon-config',
    router: '/oelCust?page=0&q=Severity!=0 and N_RecoverType=1 and (N_CustomerSeverity=1 or N_CustomerSeverity=2 or N_CustomerSeverity=3)',
  },
  {
    id: 10024,
    bpid: 1002,
    mpid: 1002,
    name: '服务台',
		icon: 'icon-config',
    router: '/monitorview',
  },
  {
    id: 10025,
    bpid: 1002,
    mpid: 1002,
    name: ozr('ZH')+'监控视图',
		icon: 'icon-config',
    router: '/centerview',
  },
  {
    id: 10026,
    bpid: 1002,
    mpid: 1002,
    name: ozr('FH')+'监控视图',
		icon: 'icon-config',
    router: '/branchview',
  },
  {
    id: 10027,
    bpid: 1002,
    mpid: 1002,
    name: '历史告警',
		icon: 'icon-config',
    router: '/historyview',
  }, {
  	id: 10028,
   	bpid: 1002,
   	mpid: 1002,
    name: 'U1历史告警',
		icon: 'area-chart',
    router: '/u1Historyview',
  }, {
  	id: 10029,
  	bpid: 1002,
  	mpid: 1002,
  	name: '短信通知',
  	icon: 'area-chart',
  	router: '/notficationView',
  },
  {
    id: 10023,
    bpid: 1002,
    mpid: 1002,
    name: 'lookup表维护',
		icon: 'icon-lookup',
    router: '/lookupGroup',
  },
  {
    id: 1003,
    name: '用户管理',
		icon: 'icon-user',
  },
  {
    id: 10031,
    bpid: 1003,
    mpid: 1003,
    name: '用户信息',
		icon: 'icon-userinfo',
    router: '/userinfo',
  }, {
    id: 10032,
    bpid: 1003,
    mpid: 1003,
    name: '角色管理',
		icon: 'icon-userroles',
    router: '/roles',
  }, {
    id: 10033,
    bpid: 1003,
    mpid: 1003,
    name: '任务管理',
    icon: 'icon-userroles',
    router: '/jobs',
  },{
    id: 1004,
    name: '维护期管理',
		icon: 'icon-user',
  }, {
    id: 10041,
    bpid: 1004,
    mpid: 1004,
    name: '模板',
		icon: 'icon-userinfo',
    router: '/maintenanceTempletGroup',
  },
  {
    id: 10042,
    bpid: 1004,
    mpid: 1004,
    name: '实例管理',
		icon: 'icon-ruleinstance',
    router: '/mainRuleInstanceGroup',
  },
  {
  	id: 1005,
  	name: '报表',
  	icon: 'icon-laptop',
  }, {
  	id: 10051,
  	bpid: 1005,
    mpid: 1005,
    name: '报表配置',
    icon: 'icon-setting',
    router: '/formConfigurationGroup',
  }, {
  	id: 10052,
  	bpid: 1005,
    mpid: 1005,
    name: '报表展现',
    icon: 'area-chart',
    router: '/formPresentationGroup',
  },
  {
    id: 1006,
    name: '监控视图',
    icon: 'area-chart',
  }, {
    id: 10061,
    bpid: 1006,
    mpid: 1006,
    name: ozr('ZH'),
    icon: 'bank',
    router: '/monitorZH',
  }, {
    id: 10062,
    bpid: 1006,
    mpid: 1006,
    name: ozr('FH'),
    icon: 'bank',
    router: '/monitorFH',
  }, {
  	id: 10063,
    bpid: 1006,
    mpid: 1006,
    name: '应用系统',
    icon: 'bank',
    router: '/appCategories',
  },
  {
    id: 1007,
    icon: 'appstore-o',
    name: '数据字典',
    router: '/dataDict',
  },
]
