export default  [
	{
		key: 'Acknowledged',
		type: 'int',
		name: '接管状态',
		core: false,
	}, {
		key: 'AdvCorrCauseType',
		type: 'int',
		name: 'AdvCorrCauseType',
		core: false,
	}, {
		key: 'AdvCorrServerName',
		type: 'string',
		name: 'AdvCorrServerName',
		core: false,
	}, {
		key: 'AdvCorrServerSerial',
		type: 'int',
		name: 'AdvCorrServerSerial',
		core: false,
	}, {
		key: 'Agent',
		type: 'string',
		name: '监控代理',
		core: true,
	}, {
		key: 'AlertGroup',
		type: 'string',
		name: '告警组',
		core: true,
	}, {
		key: 'AlertKey',
		type: 'string',
		name: '告警关键字',
		core: true,
	}, {
		key: 'Bsm_Identity',
		type: 'string',
		name: 'Bsm_Identity',
		core: false,
	}, {
		key: 'CauseType',
		type: 'int',
		name: 'CauseType',
		core: false,
	}, {
		key: 'Class',
		type: 'int',
		name: 'Class',
		core: false,
	}, {
		key: 'CorrScore',
		type: 'int',
		name: 'CorrScore',
		core: false,
	}, {
		key: 'Customer',
		type: 'string',
		name: 'Customer',
		core: false,
	}, {
		key: 'EventId',
		type: 'string',
		name: 'EventId',
		core: true,
	}, {
		key: 'ExpireTime',
		type: 'int',
		name: '过期时间',
		core: false,
	}, {
		key: 'ExtendedAttr',
		type: 'string',
		name: 'ExtendedAttr',
		core: false,
	}, {
		key: 'FirstOccurrence',
		type: 'utc',
		name: '首次告警时间',
		core: false,
	}, {
		key: 'Flash',
		type: 'int',
		name: 'Flash',
		core: false,
	}, {
		key: 'Grade',
		type: 'int',
		name: 'Grade',
		core: false,
	}, {
		key: 'Identifier',
		type: 'string',
		name: 'Identifier',
		core: true,
	}, {
		key: 'InternalLast',
		type: 'utc',
		name: 'InternalLast',
		core: false,
	}, {
		key: 'ITMApplLabel',
		type: 'string',
		name: 'ITMApplLabel',
		core: false,
	}, {
		key: 'ITMDisplayItem',
		type: 'string',
		name: 'ITMDisplayItem',
		core: false,
	}, {
		key: 'ITMEventData',
		type: 'string',
		name: 'ITMEventData',
		core: false,
	}, {
		key: 'ITMHostname',
		type: 'string',
		name: 'ITMHostname',
		core: false,
	}, {
		key: 'ITMIntType',
		type: 'string',
		name: 'ITMIntType',
		core: false,
	}, {
		key: 'ITMPort',
		type: 'string',
		name: 'ITMPort',
		core: false,
	}, {
		key: 'ITMResetFlag',
		type: 'string',
		name: 'ITMResetFlag',
		core: false,
	}, {
		key: 'ITMSitFullName',
		type: 'string',
		name: 'ITM情景名',
		core: false,
	}, {
		key: 'ITMSitGroup',
		type: 'string',
		name: 'ITM情景组',
		core: false,
	}, {
		key: 'ITMSitType',
		type: 'string',
		name: 'ITM情景类型',
		core: false,
	}, {
		key: 'ITMStatus',
		type: 'string',
		name: 'ITMStatus',
		core: false,
	}, {
		key: 'ITMThruNode',
		type: 'string',
		name: 'ITMThruNode',
		core: false,
	}, {
		key: 'ITMTime',
		type: 'string',
		name: 'ITMTime',
		core: false,
	}, {
		key: 'LastOccurrence',
		type: 'utc',
		name: '最后告警时间',
		core: false,
	}, {
		key: 'LocalNodeAlias',
		type: 'string',
		name: 'LocalNodeAlias',
		core: false,
	}, {
		key: 'LocalObjRelate',
		type: 'int',
		name: 'LocalObjRelate',
		core: false,
	}, {
		key: 'LocalPriObj',
		type: 'string',
		name: 'LocalPriObj',
		core: false,
	}, {
		key: 'LocalRootObj',
		type: 'string',
		name: 'LocalRootObj',
		core: false,
	}, {
		key: 'LocalSecObj',
		type: 'string',
		name: 'LocalSecObj',
		core: false,
	}, {
		key: 'LocalTertObj',
		type: 'string',
		name: 'LocalTertObj',
		core: false,
	}, {
		key: 'Location',
		type: 'string',
		name: 'Location',
		core: false,
	}, {
		key: 'Manager',
		type: 'string',
		name: '告警采集器',
		core: true,
	}, {
		key: 'MasterSerial',
		type: 'int',
		name: 'MasterSerial',
		core: false,
	}, {
		key: 'N_AckMode',
		type: 'int',
		name: '接管方式',
		core: false,
	}, {
		key: 'N_AckOverTime',
		type: 'int',
		name: '接管是否超时',
		core: false,
	}, {
		key: 'N_AckTime',
		type: 'utc',
		name: '接管时间',
		core: false,
	}, {
		key: 'N_AckedBy',
		type: 'string',
		name: '接管人',
		core: false,
	}, {
		key: 'N_AppCode',
		type: 'string',
		name: '应用系统代码',
		core: true,
	}, {
		key: 'N_AppName',
		type: 'string',
		name: '应用系统名称',
		core: true,
	}, {
		key: 'N_BizArea',
		type: 'string',
		name: '网络区域',
		core: true,
	}, {
		key: 'N_BizCode',
		type: 'string',
		name: '网络区域代码',
		core: false,
	}, {
		key: 'N_BizName',
		type: 'string',
		name: '网络区域名',
		core: false,
	}, {
		key: 'N_EventRemark',
		type: 'string',
		name: '处理结果',
		core: false,
	}, {
		key: 'N_ClearTime',
		type: 'utc',
		name: '恢复时间',
		core: false,
	}, {
		key: 'N_Close',
		type: 'int',
		name: '是否关闭',
		core: false,
	}, {
		key: 'N_CloseOverTime',
		type: 'int',
		name: '关闭是否超时',
		core: false,
	}, {
		key: 'N_CloseTime',
		type: 'utc',
		name: '关闭时间',
		core: false,
	}, {
		key: 'N_Component',
		type: 'string',
		name: '告警中类',
		core: true,
	}, {
		key: 'N_ComponentId',
		type: 'string',
		name: 'N_ComponentId',
		core: true,
	}, {
		key: 'N_ComponentType',
		type: 'string',
		name: '告警大类',
		core: true,
	}, {
		key: 'N_ComponentTypeId',
		type: 'string',
		name: 'N_ComponentTypeId',
		core: true,
	}, {
		key: 'N_Contact',
		type: 'string',
		name: '联系人',
		core: false,
	}, {
		key: 'N_CustomerSeverity',
		type: 'int',
		name: '告警级别',
		core: false,
	}, {
		key: 'N_Duration',
		type: 'int',
		name: '告警持续时间',
		core: false,
	}, {
		key: 'N_EventStatus',
		type: 'int',
		name: '告警状态',
		core: false,
	}, {
		key: 'N_Factory',
		type: 'string',
		name: '告警节点厂商',
		core: true,
	}, {
		key: 'N_Function',
		type: 'string',
		name: 'N_Function',
		core: false,
	}, {
		key: 'N_HWType',
		type: 'string',
		name: '硬件类型',
		core: false,
	}, {
		key: 'N_ISMMonitorType',
		type: 'int',
		name: 'N_ISMMonitorType',
		core: false,
	}, {
		key: 'N_ISMThresholdTally',
		type: 'int',
		name: 'N_ISMThresholdTally',
		core: false,
	}, {
		key: 'N_InstanceId',
		type: 'string',
		name: '告警对象',
		core: true,
	}, {
		key: 'N_InstanceSituation',
		type: 'string',
		name: 'N_InstanceSituation',
		core: true,
	}, {
		key: 'N_InstanceValue',
		type: 'string',
		name: '告警值',
		core: true,
	}, {
		key: 'N_LifecycleState',
		type: 'int',
		name: 'N_LifecycleState',
		core: false,
	}, {
		key: 'N_LineId',
		type: 'string',
		name: '专线号',
		core: false,
	}, {
		key: 'N_MachineType',
		type: 'string',
		name: 'N_MachineType',
		core: false,
	}, {
		key: 'N_MailBox',
		type: 'string',
		name: 'N_MailBox',
		core: false,
	}, {
		key: 'N_MailFlag',
		type: 'int',
		name: 'N_MailFlag',
		core: false,
	}, {
		key: 'N_MaintainBTime',
		type: 'utc',
		name: '维护期开始时间',
		core: false,
	}, {
		key: 'N_MaintainDuration',
		type: 'int',
		name: '维护期持续时间',
		core: false,
	}, {
		key: 'N_MaintainETime',
		type: 'utc',
		name: '维护期结束时间',
		core: false,
	}, {
		key: 'N_MaintainId',
		type: 'string',
		name: '维护期ID',
		core: false,
	}, {
		key: 'N_MaintainStatus',
		type: 'int',
		name: '维护期状态',
		core: false,
	}, {
		key: 'N_ManageByCenter',
		type: 'int',
		name: 'N_ManageByCenter',
		core: false,
	}, {
		key: 'N_MessageID',
		type: 'string',
		name: '原始信息ID',
		core: false,
	}, {
		key: 'N_MgtOrg',
		type: 'string',
		name: '管理机构',
		core: true,
	}, {
		key: 'N_MgtOrgId',
		type: 'string',
		name: 'N_MgtOrgId',
		core: true,
	}, {
		key: 'N_NodeName',
		type: 'string',
		name: '设备名称',
		core: true,
	}, {
		key: 'N_OSType',
		type: 'string',
		name: 'N_OSType',
		core: false,
	}, {
		key: 'N_ObjectDescr',
		type: 'string',
		name: '告警对象描述',
		core: true,
	}, {
		key: 'N_OrgId',
		type: 'string',
		name: 'N_OrgId',
		core: true,
	}, {
		key: 'N_OrgName',
		type: 'string',
		name: '所属机构',
		core: true,
	}, {
		key: 'N_OriginalSeverity',
		type: 'string',
		name: '原始级别',
		core: false,
	}, {
		key: 'N_PassedByGw',
		type: 'int',
		name: '是否同步',
		core: false,
	}, {
		key: 'N_PeerNode',
		type: 'string',
		name: 'N_PeerNode',
		core: false,
	}, {
		key: 'N_PeerPort',
		type: 'string',
		name: 'N_PeerPort',
		core: true,
	}, {
		key: 'N_Phone',
		type: 'string',
		name: 'N_Phone',
		core: false,
	}, {
		key: 'N_PolicyName',
		type: 'string',
		name: 'N_PolicyName',
		core: false,
	}, {
		key: 'N_PreSeverity',
		type: 'int',
		name: '前次级别',
		core: false,
	}, {
		key: 'N_ProviderName',
		type: 'string',
		name: '线路供应商',
		core: false,
	}, {
		key: 'N_ProviderPhone',
		type: 'string',
		name: 'N_ProviderPhone',
		core: false,
	}, {
		key: 'N_RecoverType',
		type: 'int',
		name: '是否可恢复',
		core: true,
	}, {
		key: 'N_Repository',
		type: 'string',
		name: 'N_Repository',
		core: false,
	}, {
		key: 'N_ResourceId',
		type: 'string',
		name: '资源ID',
		core: true,
	}, {
		key: 'N_ResourceUsage',
		type: 'string',
		name: 'N_ResourceUsage',
		core: false,
	}, {
		key: 'N_SMSFlag',
		type: 'int',
		name: '短信发送状态',
		core: false,
	}, {
		key: 'N_SoundFlag',
		type: 'int',
		name: 'N_SoundFlag',
		core: false,
	}, {
		key: 'N_SubComponent',
		type: 'string',
		name: '告警子类',
		core: true,
	}, {
		key: 'N_EventId',
		type: 'string',
		name: 'N_EventId',
		core: false,
	}, {
		key: 'N_EventName',
		type: 'string',
		name: 'N_EventName',
		core: false,
	}, {
		key: 'N_CiType',
		type: 'int',
		name: 'N_CiType',
		core: false,
	}, {
		key: 'N_CloseBy',
		type: 'string',
		name: '关闭人',
		core: false,
	}, {
		key: 'N_SubComponentId',
		type: 'string',
		name: 'N_SubComponentId',
		core: true,
	}, {
		key: 'N_SummaryCN',
		type: 'string',
		name: '告警描述',
		core: true,
	}, {
		key: 'N_SupportOrg',
		type: 'string',
		name: 'N_SupportOrg',
		core: false,
	}, {
		key: 'N_SuppressFirstOccurrence',
		type: 'utc',
		name: '状态变更时间',
		core: false,
	}, {
		key: 'N_TicketId',
		type: 'string',
		name: 'ITSM工单ID',
		core: false,
	}, {
		key: 'N_TicketStatus',
		type: 'string',
		name: '工单状态',
		core: false,
	}, {
		key: 'N_ZProcessState',
		type: 'int',
		name: '处理状态',
		core: false,
	}, {
		key: 'NmosCauseType',
		type: 'int',
		name: 'NmosCauseType',
		core: false,
	}, {
		key: 'NmosObjInst',
		type: 'int',
		name: 'nmosObjInst',
		core: false,
	}, {
		key: 'NmosEntityId',
		type: 'int',
		name: 'NmosEntityId',
		core: false,
	}, {
		key: 'NmosManagedStatus',
		type: 'int',
		name: 'NmosManagedStatus',
		core: false,
	}, {
		key: 'NmosSerial',
		type: 'string',
		name: 'NmosSerial',
		core: false,
	}, {
		key: 'NmosEventMap',
		type: 'string',
		name: 'NmosEventMap',
		core: false,
	}, {
		key: 'NmosDomainName',
		type: 'string',
		name: 'NmosDomainName',
		core: false,
	}, {
		key: 'Node',
		type: 'string',
		name: '主机名',
		core: true,
	}, {
		key: 'NodeAlias',
		type: 'string',
		name: 'IP地址',
		core: true,
	}, {
		key: 'OldRow',
		type: 'int',
		name: 'OldRow',
		core: false,
	}, {
		key: 'OwnerGID',
		type: 'int',
		name: 'OwnerGID',
		core: false,
	}, {
		key: 'OwnerUID',
		type: 'int',
		name: 'OwnerUID',
		core: false,
	}, {
		key: 'PhysicalCard',
		type: 'string',
		name: 'PhysicalCard',
		core: false,
	}, {
		key: 'PhysicalPort',
		type: 'int',
		name: 'PhysicalPort',
		core: false,
	}, {
		key: 'PhysicalSlot',
		type: 'int',
		name: 'PhysicalSlot',
		core: false,
	}, {
		key: 'Poll',
		type: 'int',
		name: 'Poll',
		core: false,
	}, {
		key: 'ProbeSubSecondId',
		type: 'int',
		name: 'ProbeSubSecondId',
		core: false,
	}, {
		key: 'ProcessReq',
		type: 'int',
		name: 'ProcessReq',
		core: false,
	}, {
		key: 'RemoteNodeAlias',
		type: 'string',
		name: 'RemoteNodeAlias',
		core: false,
	}, {
		key: 'RemoteObjRelate',
		type: 'int',
		name: 'RemoteObjRelate',
		core: false,
	}, {
		key: 'RemotePriObj',
		type: 'string',
		name: 'RemotePriObj',
		core: false,
	}, {
		key: 'RemoteRootObj',
		type: 'string',
		name: 'RemoteRootObj',
		core: false,
	}, {
		key: 'RemoteSecObj',
		type: 'string',
		name: 'RemoteSecObj',
		core: false,
	}, {
		key: 'RemoteTertObj',
		type: 'string',
		name: 'RemoteTertObj',
		core: false,
	}, {
		key: 'Serial',
		type: 'int',
		name: 'Serial',
		core: false,
	}, {
		key: 'ServerName',
		type: 'string',
		name: 'ServerName',
		core: true,
	}, {
		key: 'ServerSerial',
		type: 'int',
		name: 'ServerSerial',
		core: false,
	}, {
		key: 'Service',
		type: 'string',
		name: 'Service',
		core: false,
	}, {
		key: 'Severity',
		type: 'int',
		name: '级别',
		core: true,
	}, {
		key: 'StateChange',
		type: 'utc',
		name: 'StateChange',
		core: false,
	}, {
		key: 'Summary',
		type: 'string',
		name: '告警描述',
		core: true,
	}, {
		key: 'SuppressEscl',
		type: 'int',
		name: 'SuppressEscl',
		core: false,
	}, {
		key: 'Tally',
		type: 'int',
		name: '重复次数',
		core: false,
	}, {
		key: 'TaskList',
		type: 'int',
		name: 'TaskList',
		core: false,
	}, {
		key: 'TecDate',
		type: 'string',
		name: 'TecDate',
		core: false,
	}, {
		key: 'TecFQHostname',
		type: 'string',
		name: 'TecFQHostname',
		core: false,
	}, {
		key: 'TecHostname',
		type: 'string',
		name: 'TecHostname',
		core: false,
	}, {
		key: 'TecRepeatCount',
		type: 'int',
		name: 'TecRepeatCount',
		core: false,
	}, {
		key: 'Type',
		type: 'int',
		name: '告警类型',
		core: true,
	}, {
		key: 'Url',
		type: 'string',
		name: 'Url',
		core: false,
	}, {
		key: 'X733CorrNotif',
		type: 'string',
		name: 'X733CorrNotif',
		core: false,
	}, {
		key: 'X733EventType',
		type: 'int',
		name: 'X733EventType',
		core: false,
	}, {
		key: 'N_Processed',
		type: 'int',
		name: '业务处理状态',
		core: false,
	}, {
		key: 'N_ParentSerial',
		type: 'int',
		name: 'N_ParentSerial',
		core: false,
	}, {
		key: 'X733ProbableCause',
		type: 'int',
		name: 'X733ProbableCause',
		core: false,
	}, {
		key: 'X733SpecificProb',
		type: 'string',
		name: 'X733SpecificProb',
		core: false,
	}, {
		key: 'N_MainRelatedSerial',
		type: 'string',
		name: 'N_MainRelatedSerial',
		core: false,
	}, {
		key: 'N_EsclStartTime',
		type: 'utc',
		name: 'N_EsclStartTime',
		core: false,
	}, {
		key: 'N_ESCALATIONBYTIME',
		type: 'int',
		name: 'N_ESCALATIONBYTIME',
		core: false,
	}, {
		key: 'N_TRIGGERNAME',
		type: 'string',
		name: 'N_TRIGGERNAME',
		core: false,
	}, {
		key: 'N_SITRCA_FLAG',
		type: 'int',
		name: 'N_SITRCA_FLAG',
		core: false,
	}, {
		key: 'N_SITRCA_SERIAL',
		type: 'string',
		name: 'N_SITRCA_SERIAL',
		core: false,
	}, {
		key: 'N_SITRCA_RULEID',
		type: 'string',
		name: 'N_SITRCA_RULEID',
		core: false,
	}, {
		key: 'N_SITRCA_IFRCA',
		type: 'string',
		name: 'N_SITRCA_IFRCA',
		core: false,
	}, {
		key: 'N_CIGROUP',
		type: 'string',
		name: 'N_CIGROUP',
		core: false,
	}, {
		key: 'N_CIKEY',
		type: 'string',
		name: 'N_CIKEY',
		core: false,
	}, {
		key: 'N_CIKEY_SUP',
		type: 'string',
		name: 'N_CIKEY_SUP',
		core: false,
	}, {
		key: 'N_BEGIN_PORTNAME',
		type: 'string',
		name: 'N_BEGIN_PORTNAME',
		core: false,
	}, {
		key: 'N_KPI_NAME',
		type: 'string',
		name: 'N_KPI_NAME',
		core: false,
	}, {
		key: 'N_KPI_CODE',
		type: 'string',
		name: 'N_KPI_CODE',
		core: false,
	}, {
		key: 'N_KPI_PATH',
		type: 'string',
		name: 'N_KPI_PATH',
		core: false,
	}, {
		key: 'N_DIAGNOSE_CODE',
		type: 'string',
		name: 'N_DIAGNOSE_CODE',
		core: false,
	}, {
		key: 'N_DIAGNOSE_PARAMETER',
		type: 'string',
		name: 'N_DIAGNOSE_PARAMETER',
		core: false,
	}, {
		key: 'N_DIAGNOSE_CALL_CYCLE',
		type: 'string',
		name: 'N_DIAGNOSE_CALL_CYCLE',
		core: false,
	}, {
		key: 'N_Note',
		type: 'string',
		name: '备注',
		core: false,
	}, {
		key: 'NetworkAssureAlarmId',
		type: 'int',
		name: 'NetworkAssureAlarmId',
		core: false,
	}, {
		key: 'NetworkAssureHost',
		type: 'string',
		name: 'NetworkAssureHost',
		core: false,
	}, {
		key: 'NetworkAssurePort',
		type: 'int',
		name: 'NetworkAssurePort',
		core: false,
	}, {
		key: 'A_ARaw',
		type: 'string',
		name: '原始消息',
		core: false,
	}, {
		key: 'N_ExtraIP',
		type: 'string',
		name: 'N_ExtraIP',
		core: false,
	}, {
		key: 'N_GroupID',
		type: 'int',
		name: 'N_GroupID',
		core: false,
	}, {
		key: 'N_LineEn',
		type: 'string',
		name: 'N_LineEn',
		core: false,
	}, {
		key: 'N_LogRecord',
		type: 'string',
		name: 'N_LogRecord',
		core: false,
	}, {
		key: 'N_Room',
		type: 'string',
		name: '机房',
		core: false,
	}, {
		key: 'N_MonitorLocation',
		type: 'string',
		name: 'N_MonitorLocation',
		core: false,
	}, {
		key: 'N_DaPingFlag',
		type: 'int',
		name: 'N_DaPingFlag',
		core: false,
	}, {
		key: 'N_STRATEGY',
		type: 'string',
		name: 'N_STRATEGY',
		core: false,
	}, {
		key: 'N_ReceiveTime',
		type: 'utc',
		name: 'N_ReceiveTime',
		core: false,
	}, {
		key: 'N_NPassHis',
		type: 'int',
		name: '是否归档',
		core: false,
	}, {
		key: 'N_InsertFlag',
		type: 'int',
		name: 'N_InsertFlag',
		core: false,
	}, {
		key: 'N_GroupName',
		type: 'string',
		name: 'N_GroupName',
		core: false,
	}, {
		key: 'N_DWDM',
		type: 'string',
		name: 'N_DWDM',
		core: false,
	}, {
		key: 'N_NoticeGroup',
		type: 'string',
		name: 'N_NoticeGroup',
		core: false,
	}, {
		key: 'N_PassedByUni',
		type: 'int',
		name: '是否同步',
		core: false,
	}, {
		key: 'OZ_OrgCode',
		type: 'string',
		name: '采集器所在机构代码',
		core: false,
	}, {
		key: 'OZ_OrgName',
		type: 'string',
		name: '采集器所在机构',
		core: false,
	}, {
		key: 'OZ_MoID',
		type: 'string',
		name: '监控对象ID',
		core: false,
	}, {
		key: 'OZ_MoName',
		type: 'string',
		name: '监控对象名称',
		core: false,
	}, {
		key: 'OZ_PolicyTemplateID',
		type: 'string',
		name: 'OZ_PolicyTemplateID',
		core: false,
	}, {
		key: 'OZ_PolicyInstanceID',
		type: 'string',
		name: 'OZ_PolicyInstanceID',
		core: false,
	}, {
		key: 'OZ_IndicatiorID',
		type: 'string',
		name: 'OZ_IndicatiorID',
		core: false,
	}, {
		key: 'OZ_MonitorTool',
		type: 'string',
		name: 'OZ_MonitorTool',
		core: false,
	}, {
		key: 'OZ_MonitorToolInstanceID',
		type: 'string',
		name: 'OZ_MonitorToolInstanceID',
		core: false,
	}, {
		key: 'OZ_MonitorInstanceID',
		type: 'string',
		name: 'OZ_MonitorInstanceID',
		core: false,
	}, {
		key: 'OZ_MaintainEnterTime',
		type: 'utc',
		name: '首次进入维护期时间',
		core: false,
	}, {
		key: 'OZ_MaintainEnterSeq',
		type: 'string',
		name: '当前进入维护期ID',
		core: false,
	}, {
		key: 'OZ_MaintainEnterHis',
		type: 'string',
		name: '维护期历史序列',
		core: false,
	}, {
		key: 'TECRepeatCount',
		type: 'int',
		name: 'TECRepeatCount',
		core: false,
	}, {
		key: 'BSM_Identity',
		type: 'string',
		name: 'BSM_Identity',
		core: false,
	}, {
		key: 'CollectionFirst',
		type: 'utc',
		name: '首次进入采集层时间',
		core: false,
	}, {
		key: 'OZ_TicketSender',
		type: 'string',
		name: '工单发送人',
		core: false,
	}, {
		key: 'OZ_TicketTime',
		type: 'utc',
		name: '工单发送时间',
		core: false,
	}, {
		key: 'OZ_EsclTime',
		type: 'utc',
		name: 'OZ_EsclTime',
		core: false,
	}, {
		key: 'OZ_RecoverTime',
		type: 'utc',
		name: 'OZ_RecoverTime',
		core: false,
	}, {
		key: 'OZ_FirstOccurrence',
		type: 'utc',
		name: 'OZ_FirstOccurrence',
		core: false,
	}, {
		key: 'OZ_LastDuration',
		type: 'int',
		name: 'OZ_LastDuration',
		core: false,
	}, {
    key: 'OZ_MaintainProcess',
    type: 'int',
    name: 'OZ_MaintainProcess',
    core: true,
  }, {
    key: 'OZ_ReInFirstOccurrence',
    type: 'utc',
    name: 'OZ_ReInFirstOccurrence',
    core: true,
  }, {
		key: 'DisplayFirst',
		type: 'utc',
		name: '首次进入显示层时间',
		core: false,
	}, {
		key: 'OZ_TicketResult',
		type: 'string',
		name: '工单结果详情',
		core: false,
	}, {
		key: 'TECHostname',
		type: 'string',
		name: 'TECHostname',
		core: false,
	}, {
		key: 'TECDate',
		type: 'string',
		name: 'TECDate',
		core: false,
	}, {
		key: 'OZ_ExitMTime',
		type: 'utc',
		name: 'OZ_ExitMTime',
		core: false,
	}, {
		key: 'AggregationFirst',
		type: 'utc',
		name: '首次进入汇聚层时间',
		core: false,
	}, {
		key: 'URL',
		type: 'string',
		name: 'URL',
		core: false,
	}, {
		key: 'TECFQHostname',
		type: 'string',
		name: 'TECFQHostname',
		core: false,
	}, {
		key: 'OZ_AlarmID',
		type: 'string',
		name: '告警序列号',
		core: true,
	},
]
