export default  [{
    label: '操作系统',
    value: '操作系统-OperatingSystem',
    key: 'OperatingSystem-0-0',
    children: [{
      label: 'AIX',
      value: 'AIX-AIX',
      key: 'AIX-0-0-0',
      children: [
        { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-0-0-0' },
        { label: '磁盘', value: '磁盘-Disk', key: 'Disk-0-0-0-1' },
        { label: '服务', value: '服务-Service', key: 'Service-0-0-0-2' },
        { label: '交换区', value: '交换区-Swap', key: 'Swap-0-0-0-3' },
        { label: '进程', value: '进程-Process', key: 'Process-0-0-0-4' },
        { label: '链路', value: '链路-Link', key: 'Link-0-0-0-5' },
        { label: '内存', value: '内存-Memory', key: 'Memory-0-0-0-6' },
        { label: '日志', value: '日志-LogFile', key: 'LogFile-0-0-0-7' },
        { label: '网卡', value: '网卡-Netinterface', key: 'Netinterface-0-0-0-8' },
        { label: '网络', value: '网络-Network', key: 'Network-0-0-0-9' },
        { label: '文件', value: '文件-File', key: 'File-0-0-0-10' },
        { label: '文件系统', value: '文件系统-FileSystem', key: 'FileSystem-0-0-0-11' },
        { label: '硬件', value: '硬件-Hardware', key: 'Hardware-0-0-0-12' },
      ],
    }, {
      label: 'HPUX',
      value: 'HPUX-HPUX',
      key: 'HPUX-0-0-1',
      children: [
        { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-0-1-0' },
        { label: '磁盘', value: '磁盘-Disk', key: 'Disk-0-0-1-1' },
        { label: '服务', value: '服务-Service', key: 'Service-0-0-1-2' },
        { label: '集群', value: '集群-Cluster', key: 'Cluster-0-0-1-3' },
        { label: '交换区', value: '交换区-Swap', key: 'Swap-0-0-1-4' },
        { label: '进程', value: '进程-Process', key: 'Process-0-0-1-5' },
        { label: '链路', value: '链路-Link', key: 'Link-0-0-1-6' },
        { label: '内存', value: 'Memory', key: 'Memory-0-0-1-7' },
        { label: '内核', value: '内存-Kernel', key: 'Kernel-0-0-1-8' },
        { label: '日志', value: '日志-LogFile', key: 'LogFile-0-0-1-9' },
        { label: '网卡', value: '网卡-Netinterface', key: 'Netinterface-0-0-1-10' },
        { label: '网络', value: '网络-Network', key: 'Network-0-0-1-11' },
        { label: '文件', value: '文件-File', key: 'File-0-0-1-12' },
        { label: '文件系统', value: '文件系统-FileSystem', key: 'FileSystem-0-0-1-13' },
        { label: '硬件', value: '硬件-Hardware', key: 'Hardware-0-0-1-14' },
      ],
    }, {
      label: 'Linux',
      value: 'Linux-Linux',
      key: 'Linux-0-0-2',
      children: [
        { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-0-2-0' },
        { label: '磁盘', value: '磁盘-Disk', key: 'Disk-0-0-2-1' },
        { label: '服务', value: '服务-Service', key: 'Service-0-0-2-2' },
        { label: '交换区', value: '交换区-Swap', key: 'Swap-0-0-2-3' },
        { label: '进程', value: '进程-Process', key: 'Process-0-0-2-4' },
        { label: '链路', value: '链路-Link', key: 'Link-0-0-2-5' },
        { label: '内存', value: '内存-Memory', key: 'Memory-0-0-2-6' },
        { label: '日志', value: '日志-LogFile', key: 'LogFile-0-0-2-7' },
        { label: '网卡', value: '网卡-Netinterface', key: 'Netinterface-0-0-2-8' },
        { label: '网络', value: '网络-Network', key: 'Network-0-0-2-9' },
        { label: '文件', value: '文件-File', key: 'File-0-0-2-10' },
        { label: '文件系统', value: '文件系统-FileSystem', key: 'FileSystem-0-0-2-11' },
      ],
    }, {
      label: 'Unknown',
      value: 'Unknown-Unknown',
      key: 'Unknown-0-0-3',
      children: [
        { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-0-3-0' },
        { label: '交换区', value: '交换区-Swap', key: 'Swap-0-0-3-1' },
        { label: '节点', value: '节点-Node', key: 'Node-0-0-3-2' },
        { label: '进程', value: '进程-Process', key: 'Process-0-0-3-3' },
        { label: '内存', value: '内存-Memory', key: 'Memory-0-0-3-4' },
        { label: '文件系统', value: '文件系统-FileSystem', key: 'FileSystem-0-0-3-5' },
        { label: '用户', value: '用户-User', key: 'User-0-0-3-6' },
      ],
    }, {
      label: 'Windows',
      value: 'Windows-Windows',
      key: 'Windows-0-0-4',
      children: [
        { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-0-4-0' },
        { label: '磁盘', value: '磁盘-Disk', key: 'Disk-0-0-4-1' },
        { label: '服务', value: '服务-Service', key: 'Service-0-0-4-2' },
        { label: '交换区', value: '交换区-Swap', key: 'Swap-0-0-4-3' },
        { label: '进程', value: '进程-Process', key: 'Process-0-0-4-4' },
        { label: '内存', value: '内存-Memory', key: 'Memory-0-0-4-5' },
        { label: '日志', value: '日志-LogFile', key: 'LogFile-0-0-4-6' },
        { label: '网卡', value: '网卡-Netinterface', key: 'Netinterface-0-0-4-7' },
        { label: '网络', value: '网络-Network', key: 'Network-0-0-4-8' },
        { label: '文件系统', value: '文件系统-FileSystem', key: 'FileSystem-0-0-4-9' },
        { label: '硬件', value: '硬件-Hardware', key: 'Hardware-0-0-4-10' },
      ],
    }, {
      label: '集群',
      value: '集群-VCS',
      key: 'VCS-0-0-5',
      children: [
        { label: '进程', value: '进程-Process', key: 'Process-0-0-5-0' },
        { label: '日志', value: '日志-Logfile', key: 'Logfile-0-0-5-1' },
      ],
    }, {
      label: 'PING',
      value: 'PING-null',
      key: 'PING-null-0-0-6',
      children: [
        { label: 'PING', value: 'PING-PING', key: 'PING-0-0-6-0' },
      ],
    }],
  }, {
    label: '存储',
    value: '存储-Storage',
    key: 'Storage-0-1',
    children: [
      {
        label: 'Unknown',
        value: 'Unknown-Unknown',
        key: 'Unknown-0-1-0',
      }, {
        label: '存储',
        value: '存储-Storage',
        key: 'Storage-0-1-1',
        children: [
          { label: '进程', value: '进程-Process', key: 'Process-0-1-1-0' },
          { label: '日志', value: '日志-Logfile', key: 'Logfile-0-1-1-1' },
        ],
      }, {
        label: '高端存储',
        value: '高端存储-EMCSymmetrix',
        key: 'EMCSymmetrix-0-1-2',
        children: [
          { label: '部件', value: '部件-Component', key: 'Component-0-1-2-0' },
          { label: '磁盘', value: '磁盘-Disk', key: 'Disk-0-1-2-1' },
          { label: '电源', value: '电源-Power', key: 'Power-0-1-2-2' },
          { label: '队列', value: '队列-Queue', key: 'Queue-0-1-2-3' },
          { label: '进程', value: '进程-Process', key: 'Process-0-1-2-4' },
          { label: '日志', value: '日志-Logfile', key: 'Logfile-0-1-2-5' },
          { label: '硬盘', value: '硬盘-HardDisk', key: 'HardDisk-0-1-2-6' },
          { label: '内存', value: '内存-Memory', key: 'Memory-0-1-2-7' },
          { label: '处理器', value: '处理器-Director', key: 'Director-0-1-2-8' },
          { label: '端口', value: '端口-Port', key: 'Port-0-1-2-9' },
          { label: 'SPF', value: 'SPF-SPF', key: 'SPF-0-1-2-10' },
          { label: '电源', value: '电源-Power', key: 'Power-0-1-2-11' },
          { label: '电池', value: '电池-Battery', key: 'Battery-0-1-2-12' },
          { label: '风扇', value: '风扇-Fan', key: 'Fan-0-1-2-13' },
          { label: '温度', value: '温度-Temperature', key: 'Temperature-0-1-2-14' },
          { label: '链路控制卡', value: '链路控制卡-LCC', key: 'LCC-0-1-2-15' },
          { label: 'SG', value: 'SG-SG', key: 'SG-0-1-2-16' },
          { label: 'VMX', value: 'VMX-VMX', key: 'VMX-0-1-2-17' },
          { label: 'DMX', value: 'DMX-DMX', key: 'DMX-0-1-2-18' },
        ],
      }, {
        label: '中端存储',
        value: '中端存储-EMCVnx',
        key: 'EMCVnx-0-1-3',
        children: [
          { label: 'VNX', value: 'VNX-VNX', key: 'VNX-0-1-3-0' },
          { label: 'NS480', value: 'NS480-NS480', key: 'NS480-0-1-3-1' },
          { label: '控制器', value: '控制器-Controller', key: 'Controller-0-1-3-2' },
          { label: '电源', value: '电源-Power', key: 'Power-0-1-3-3' },
          { label: '电池', value: '电池-Battery', key: 'Battery-0-1-3-4' },
          { label: 'Cache', value: 'Cache-Cache', key: 'Cache-0-1-3-5' },
          { label: '电源线', value: '电源线-PowerLine', key: 'PowerLine-0-1-3-6' },
          { label: '温度', value: '温度-Temperature', key: 'Temperature-0-1-3-7' },
          { label: '硬盘', value: '硬盘-HardDisk', key: 'HardDisk-0-1-3-8' },
          { label: '硬盘笼', value: '硬盘笼-HardDiskCage', key: 'HardDiskCage-0-1-3-9' },
        ],
      }, {
        label: '光纤交换机',
        value: '光纤交换机-FSwitch',
        key: 'FSwitch-0-1-4',
        children: [
          { label: '博科', value: '博科-Brocade', key: 'Brocade-0-1-4-0' },
          { label: '端口', value: '端口-Port', key: 'Port-0-1-4-1' },
          { label: '交换机', value: '交换机-Switch', key: 'Switch-0-1-4-2' },
          { label: '风扇', value: '风扇-Fan', key: 'Fan-0-1-4-3' },
          { label: '电源', value: '电源-Power', key: 'Power-0-1-4-4' },
          { label: '温度', value: '温度-Temperature', key: 'Temperature-0-1-4-5' },
        ],
      },
    ],
  }, {
    label: '数据库',
    value: '数据库-Database',
    key: 'Database-0-2',
    children: [{
      label: 'DB2',
      value: 'DB2-DB2',
      key: 'DB2-0-2-0',
      children: [
        { label: '表空间', value: '表空间-TableSpace', key: 'TableSpace-0-2-0-0' },
        { label: '日志', value: '日志-LogFile', key: 'LogFile-0-2-0-1' },
        { label: '实例', value: '实例-Instance', key: 'Instance-0-2-0-2' },
        { label: '死锁', value: '死锁-DeadLock', key: 'DeadLock-0-2-0-3' },
        { label: '锁', value: '锁-Lock', key: 'Lock-0-2-0-4' },
      ],
    }, {
      label: 'Mysql',
      value: 'Mysql-Mysql',
      key: 'Mysql-0-2-1',
      children: [
        { label: '进程', value: '进程-Process', key: 'Process-0-2-1-0' },
        { label: '状态', value: '状态-Status', key: 'Status-0-2-1-1' },
      ],
    }, {
      label: 'Oracle',
      value: 'Oracle-Oracle',
      key: 'Oracle-0-2-2',
      children: [
        { label: 'CustomSql', value: 'CustomSql-CustomSql', key: 'CustomSql-0-2-2-0' },
        { label: 'Redo日志', value: 'Redo日志-RedoLog', key: 'RedoLog-0-2-2-1' },
        { label: 'SGA', value: 'SGA-SGA', key: 'SGA-0-2-2-2' },
        { label: 'SQL性能', value: 'SQL性能-SQL_Perf', key: 'SQL_Perf-0-2-2-3' },
        { label: 'SQL语句', value: 'SQL语句-SQL', key: 'SQL-0-2-2-4' },
        { label: '告警日志', value: '告警日志-AlertLog', key: 'AlertLog-0-2-2-5' },
        { label: '表', value: '表-Tables', key: 'Tables-0-2-2-6' },
        { label: '表空间', value: '表空间-Tablespace', key: 'Tablespace-0-2-2-7' },
        { label: '触发器', value: '触发器-Trigger', key: 'Trigger-0-2-2-8' },
        { label: '传输延迟', value: '传输延迟-ReceiveLag', key: 'ReceiveLag-0-2-2-9' },
        { label: '磁盘', value: '磁盘-Disk', key: 'Disk-0-2-2-10' },
        { label: '磁盘组', value: '磁盘组-DiskGroup', key: 'DiskGroup-0-2-2-11' },
        { label: '打开状态', value: '打开状态-OpenMode', key: 'OpenMode-0-2-2-12' },
        { label: '归档', value: '归档-Archive', key: 'Archive-0-2-2-13' },
        { label: '缓存', value: '缓存-Cache', key: 'Cache-0-2-2-14' },
        { label: '恢复状态', value: '恢复状态-RecoverMode', key: 'RecoverMode-0-2-2-15' },
        { label: '会话', value: '会话-Session', key: 'Session-0-2-2-16' },
        { label: '监听', value: '监听-Listener', key: 'Listener-0-2-2-17' },
        { label: '进程', value: '进程-Process', key: 'Process-0-2-2-18' },
        { label: '连接', value: '连接-Connection', key: 'Connection-0-2-2-19' },
        { label: '排序', value: '排序-Sort', key: 'Sort-0-2-2-20' },
        { label: '日志', value: '日志-LogFile', key: 'LogFile-0-2-2-21' },
        { label: '闪回空间', value: '闪回空间-FlashArea', key: 'FlashArea-0-2-2-22' },
        { label: '闪回时间', value: '闪回时间-FlashBackTime', key: 'FlashBackTime-0-2-2-23' },
        { label: '实例', value: '实例-Instance', key: 'Instance-0-2-2-24' },
        { label: '数据对象', value: '数据对象-DataObj', key: 'DataObj-0-2-2-25' },
        { label: '数据库约束', value: '数据库约束-Constraint', key: 'Constraint-0-2-2-26' },
        { label: '数据文件', value: '数据文件-DataFiles', key: 'DataFiles-0-2-2-27' },
        { label: '索引', value: '索引-Index', key: 'Index-0-2-2-28' },
        { label: '锁', value: '锁-Lock', key: 'Lock-0-2-2-29' },
        { label: '文件', value: '文件-File', key: 'File-0-2-2-30' },
        { label: '序列号', value: '序列号-Sequence', key: 'Sequence-0-2-2-31' },
        { label: '应用延迟', value: '应用延迟-ApplyLag', key: 'ApplyLag-0-2-2-32' },
        { label: '状态', value: '状态-Status', key: 'Status-0-2-2-33' },
        { label: '会话资源', value: '会话资源-Sessions', key: 'Sessions-0-2-2-34' },
        { label: '进程资源', value: '进程资源-Processes', key: 'Processes-0-2-2-35' },
        { label: '磁盘头', value: '磁盘头-DiskHead', key: 'DiskHead-0-2-2-36' },
      ],
    }, {
      label: 'SqlServer',
      value: 'SqlServer-SqlServer',
      key: 'SqlServer-0-2-3',
      children: [
        { label: 'DataBase', value: 'DataBase-DataBase', key: 'DataBase-0-2-3-0' },
        { label: 'LogSpace', value: 'LogSpace-LogSpace', key: 'LogSpace-0-2-3-1' },
        { label: 'Server', value: 'Server-Server', key: 'Server-0-2-3-2' },
      ],
    }, {
      label: 'Unknown',
      value: 'Unknown-Unknown',
      key: 'Unknown-0-2-4',
      children: [
        { label: '其他', value: '其他-Other', key: 'Other-0-2-4-0' },
      ],
    }, {
      label: '金仓',
      value: '金仓-Kingbase',
      key: 'Kingbase-0-2-5',
      children: [
        { label: 'SQL性能', value: 'SQL性能-SQL_Perf', key: 'SQL_Perf-0-2-5-0' },
        { label: '表空间', value: '表空间-Tablespace', key: 'Tablespace-0-2-5-1' },
        { label: '会话', value: '会话-Session', key: 'Session-0-2-5-2' },
        { label: '日志', value: '日志-LogFile', key: 'LogFile-0-2-5-3' },
        { label: '事务', value: '事务-Transaction', key: 'Transaction-0-2-5-4' },
        { label: '数据文件', value: '数据文件-Datafile', key: 'Datafile-0-2-5-5' },
        { label: '锁', value: '锁-Lock', key: 'Lock-0-2-5-6' },
        { label: '网闸', value: '网闸-GAP', key: 'GAP-0-2-5-7' },
        { label: '状态', value: '状态-Status', key: 'Status-0-2-5-8' },
      ],
    }],
  }, {
    label: '网络',
    value: '网络-NetWork',
    key: 'NetWork-0-3',
    children: [{
      label: 'SSL',
      value: 'SSL-SSL',
      key: 'SSL-0-3-0',
      children: [
        { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-3-0-0' },
        { label: 'HTTPS连接', value: 'HTTPS连接-HTTPSConnection', key: 'HTTPSConnection-0-3-0-1' },
        { label: 'HTTP连接', value: 'HTTP连接-HTTPConnection', key: 'HTTPConnection-0-3-0-2' },
        { label: 'TCP连接', value: 'TCP连接-TCPConnection', key: 'TCPConnection-0-3-0-3' },
        { label: '节点', value: '节点-Node', key: 'Node-0-3-0-4' },
        { label: '内存', value: '内存-Memory', key: 'Memory-0-3-0-5' },
        { label: '响应时间', value: '响应时间-ResponseTime', key: 'ResponseTime-0-3-0-6' },
      ],
    }, {
      label: 'Unknown',
      value: 'Unknown-Unknown',
      key: 'Unknown-0-3-1',
      children: [
        { label: 'Unknown', value: 'Unknown-Unknown', key: 'Unknown-0-3-1-0' },
      ],
    }, {
      label: '负载均衡器',
      value: '负载均衡器-LoadBalancer',
      key: 'LoadBalancer-0-3-2',
      children: [
        { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-3-2-0' },
        { label: 'Memory', value: 'Memory-Memory', key: 'Memory-0-3-2-1' },
        { label: '会话', value: '会话-Session', key: 'Session-0-3-2-2' },
        { label: '节点', value: '节点-Node', key: 'Node-0-3-2-3' },
      ],
    }, {
    	  label: '其他告警类',
      value: '其他告警类',
      key: 'null-0-3-3',
      children: [
        { label: '其他告警类（PING）', value: '其他告警类-PING', key: 'PING-0-3-3-0' },
        { label: '其他告警类（BANDWIDTH）', value: '其他告警类-BANDWIDTH', key: 'BANDWIDTH-0-3-3-1' },
        { label: '其他告警类（CPU）', value: '其他告警类-CPU', key: 'CPU-0-3-3-2' },
      ],
    },{
      label: '所有设备',
    value: '所有设备-all',
    key: 'all-0-3-3',
    children: [
      { label: 'cpu', value: 'cpu-cpu', key: 'cpu' },
      { label: '内存', value: '内存-内存', key: '内存' },
      { label: '端口', value: '端口-端口', key: '端口' },
      { label: 'PING', value: 'PING-PING', key: 'PING' },
    ],
  }, {
    	  label: 'RPING',
      value: 'RPING-null',
      key: 'RPING-null-0-3-4',
      children: [
	    { label: '连通性', value: '连通性-RPING', key: 'RPING-0-3-4-0' },
	    { label: 'RPING-Other', value: 'null-null', key: 'null-0-3-4-1' },
      ],
    }, {
    	  label: '路由器',
      value: '路由器-ROUTER',
      key: 'ROUTER-0-3-5',
      children: [
	    { label: 'PING', value: 'PING-PING', key: 'PING-0-3-5-0' },
	    { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-3-5-1' },
	    { label: '内存', value: '内存-Memory', key: 'Memory-0-3-5-2' },
	    { label: '端口', value: '端口-Port', key: 'Port-0-3-5-3' },
      ],
    }, {
    	  label: '交换机',
      value: '交换机-Switch',
      key: 'Switch-0-3-6',
      children: [
	    { label: 'PING', value: 'PING-PING', key: 'PING-0-3-6-0' },
	    { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-3-6-1' },
	    { label: '内存', value: '内存-Memory', key: 'Memory-0-3-6-2' },
	    { label: '端口', value: '端口-Port', key: 'Port-0-3-6-3' },
      ],
    }, {
    	  label: '防火墙',
      value: '防火墙-FIREWALL',
      key: 'FIREWALL-0-3-7',
      children: [
	    { label: 'PING', value: 'PING-PING', key: 'PING-0-3-7-0' },
	    { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-3-7-1' },
	    { label: '内存', value: '内存-Memory', key: 'Memory-0-3-7-2' },
	    { label: '端口', value: '端口-Port', key: 'Port-0-3-7-3' },
	    { label: 'SESSION', value: 'SESSION-SESSION', key: 'SESSION-0-3-7-4' },
      ],
    }, {
    	  label: '网点IP',
      value: '网点IP-BRANCHIP',
      key: 'BRANCHIP-0-3-8',
      children: [
	    { label: 'PING', value: 'PING-PING', key: 'PING-0-3-8-0' },
      ],
    }, {
    	  label: '线路',
      value: '线路-LINE',
      key: 'LINE-0-3-9',
      children: [
	    { label: 'RPING', value: 'RPING-RPING', key: 'RPING-0-3-9-0' },
      ],
    },{
    label: '网络管理器',
    value: '网络管理器-NETManager',
    key: 'NETManager-0-3-10',
    children: [
    { label: 'PING', value: 'PING-PING', key: 'PING-0-3-10-0' },
    ],
  }],
  }, {
    label: '应用',
    value: '应用-Application',
    key: 'Application-0-4',
    children: [{
      label: 'GTS',
      value: 'GTS-GTS',
      key: 'GTS-0-4-0',
      children: [
        { label: '图形化前端', value: '图形化前端-GTS', key: 'GTS-0-4-0-0' },
      ],
    }, {
      label: 'Oracle',
      value: 'Oracle-Oracle',
      key: 'Oracle-0-4-1',
      children: [
        { label: 'CustomSql', value: 'CustomSql-CustomSql', key: 'CustomSql-0-4-1-0' },
      ],
    }, {
      label: '负载均衡器',
      value: '负载均衡器-LoadBalancer',
      key: 'LoadBalancer-0-4-2',
      children: [
        { label: '可用性', value: '可用性-availability', key: 'availability-0-4-2-0' },
      ],
    }, {
      label: '应用',
      value: '应用-Application',
      key: 'Application-0-4-3',
      children: [
        { label: 'Core文件', value: 'Core文件-Core', key: 'Core-0-4-3-0' },
        { label: '登录', value: '登录-login', key: 'login-0-4-3-1' },
        { label: '端口', value: '端口-Port', key: 'Port-0-4-3-2' },
        { label: '队列', value: '队列-Queue', key: 'Queue-0-4-3-3' },
        { label: '服务', value: '服务-Service', key: 'Service-0-4-3-4' },
        { label: '会话', value: '会话-Session', key: 'Session-0-4-3-5' },
        { label: '交易', value: '交易-Transaction', key: 'Transaction-0-4-3-6' },
        { label: '交易成功率', value: '交易成功率-SuccessRate', key: 'SuccessRate-0-4-3-7' },
        { label: '交易响应时间', value: '交易响应时间-ResponseTime', key: 'ResponseTime-0-4-3-8' },
        { label: '脚本', value: '脚本-Script', key: 'Script-0-4-3-9' },
        { label: '进程', value: '进程-Process', key: 'Process-0-4-3-10' },
        { label: '垃圾回收', value: '垃圾回收-GC', key: 'GC-0-4-3-11' },
        { label: '连接', value: '连接-Connection', key: 'Connection-0-4-3-12' },
        { label: '链路', value: '链路-Link', key: 'Link-0-4-3-13' },
        { label: '内存', value: '内存-Memory', key: 'Memory-0-4-3-14' },
        { label: '批量', value: '批量-Batch', key: 'Batch-0-4-3-15' },
        { label: '日志', value: '日志-LogFile', key: 'LogFile-0-4-3-16' },
        { label: '文件', value: '文件-File', key: 'File-0-4-3-17' },
        { label: '响应时间', value: '响应时间-ResponseTime', key: 'ResponseTime-0-4-3-18' },
        { label: '虚拟化', value: '虚拟化-VMware', key: 'VMware-0-4-3-19' },
        { label: '页面', value: '页面-WebPage', key: 'WebPage-0-4-3-20' },
        { label: '应用', value: '应用-Application', key: 'Application-0-4-3-21' },
        { label: '站点', value: '站点-WebSite', key: 'WebSite-0-4-3-22' },
        { label: '状态', value: '状态-Status', key: 'Status-0-4-3-23' },
        { label: '作业', value: '作业-Task', key: 'Task-0-4-3-24' },
      ],
    }],
  }, {
    label: '中间件',
    value: '中间件-Middleware',
    key: 'Middleware-0-5',
    children: [{
      label: 'Java',
      value: 'Java-Java',
      key: 'Java-0-5-0',
      children: [
        { label: '垃圾回收', value: '垃圾回收-GC', key: 'GC-0-5-0-0' },
      ],
    }, {
      label: 'MQ',
      value: 'MQ-MQ',
      key: 'MQ-0-5-1',
      children: [
        { label: '队列', value: '队列-Queue', key: 'Queue-0-5-1-0' },
        { label: '队列管理器', value: '队列管理器-QueueManager', key: 'QueueManager-0-5-1-1' },
        { label: '监听', value: '监听-Listener', key: 'Listener-0-5-1-2' },
        { label: '日志', value: '日志-LogFile', key: 'LogFile-0-5-1-3' },
        { label: '通道', value: '通道-Channel', key: 'Channel-0-5-1-4' },
      ],
    }, {
      label: 'Tomcat',
      value: 'Tomcat-Tomcat',
      key: 'Tomcat-0-5-2',
      children: [
        { label: '会话', value: '会话-Session', key: 'Session-0-5-2-0' },
        { label: '线程', value: '线程-Thread', key: 'Thread-0-5-2-1' },
      ],
    }, {
      label: 'Tuxedo',
      value: 'Tuxedo-Tuxedo',
      key: 'Tuxedo-0-5-3',
      children: [
        { label: '队列', value: '队列-Queue', key: 'Queue-0-5-3-0' },
        { label: '服务', value: '服务-Service', key: 'Service-0-5-3-1' },
        { label: '进程', value: '进程-Process', key: 'Process-0-5-3-2' },
        { label: '链路', value: '链路-Link', key: 'Link-0-5-3-3' },
        { label: '日志', value: '日志-LogFile', key: 'LogFile-0-5-3-4' },
        { label: '网关', value: '网关-GWTDOMAIN', key: 'GWTDOMAIN-0-5-3-5' },
      ],
    }, {
      label: 'Weblogic',
      value: 'Weblogic-Weblogic',
      key: 'Weblogic-0-5-4',
      children: [
        { label: 'JDBC', value: 'JDBC-JDBC', key: 'JDBC-0-5-4-0' },
        { label: 'JVM', value: 'JVM-JVM', key: 'JVM-0-5-4-1' },
        { label: 'WTC', value: 'WTC-WTC', key: 'WTC-0-5-4-2' },
        { label: '端口', value: '端口-Port', key: 'Port-0-5-4-3' },
        { label: '队列', value: '队列-Queue', key: 'Queue-0-5-4-4' },
        { label: '垃圾回收', value: '垃圾回收-GC', key: 'GC-0-5-4-5' },
        { label: '日志', value: '日志-LogFile', key: 'LogFile-0-5-4-6' },
        { label: '应用', value: '应用-Application', key: 'Application-0-5-4-7' },
        { label: '状态', value: '状态-Status', key: 'Status-0-5-4-8' },
      ],
    }],
  }, {
    label: '自检',
    value: '自检-SelfCheck',
    key: 'SelfCheck-0-6',
    children: [{
      label: 'OpenView',
      value: 'OpenView-OpenView',
      key: 'OpenView-0-6-0',
      children: [
        { label: '进程', value: '进程-Process', key: 'Process-0-6-0-0' },
        { label: '状态', value: '状态-Status', key: 'Status-0-6-0-1' },
        { label: '作业', value: '作业-Task', key: 'Task-0-6-0-2' },
      ],
    }, {
      label: 'Tivoli',
      value: 'Tivoli-Tivoli',
      key: 'Tivoli-0-6-1',
      children: [
        { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-6-1-0' },
        { label: '磁盘 ', value: '磁盘-Disk', key: 'Disk-0-6-1-1' },
        { label: '存储', value: '存储-Storage', key: 'Storage-0-6-1-2' },
        { label: '服务', value: '服务-Service', key: 'Service-0-6-1-3' },
        { label: '交换区', value: '交换区-Swap', key: 'Swap-0-6-1-4' },
        { label: '连接', value: '连接-Connection', key: 'Connection-0-6-1-5' },
        { label: '执行错误', value: '执行错误-ProcessError', key: 'ProcessError-0-6-1-6' },
      ],
    }, {
      label: 'Windows',
      value: 'Windows-Windows',
      key: 'Windows-0-6-2',
      children: [
        { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-6-2-0' },
        { label: '磁盘 ', value: '磁盘-Disk', key: 'Disk-0-6-2-1' },
        { label: '内存', value: '内存-Memory', key: 'Memory-0-6-2-2' },
      ],
    }, {
      label: '自检',
      value: '自检-SelfCheck',
      key: 'SelfCheck-0-6-3',
      children: [
        { label: '端口', value: '端口-Port', key: 'Port-0-6-3-0' },
        { label: '文件', value: '文件-File', key: 'File-0-6-3-1' },
      ],
    }],
  }, {
    label: '硬件',
    value: '硬件-HardWare',
    key: 'HardWare-0-7',
    children: [{
      label: 'HP服务器',
      value: 'HP服务器-HP',
      key: 'HP-0-7-0',
      children: [
        { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-7-0-0' },
        { label: '内存', value: '内存-Memory', key: 'Memory-0-7-0-1' },
        { label: '网卡', value: '网卡-NIC', key: 'NIC-0-7-0-2' },
        { label: '电源', value: '电源-Power', key: 'Power-0-7-0-3' },
        { label: '物理盘', value: '物理盘-HardDisk', key: 'HardDisk-0-7-0-4' },
        { label: '风扇', value: '风扇-Fan', key: 'Fan-0-7-0-5' },
        { label: '光纤卡', value: '光纤卡-FC_Card', key: 'FC_Card-0-7-0-6' },
        { label: '机箱', value: '机箱-Rack', key: 'Rack-0-7-0-7' },
        { label: '主板插槽', value: '主板插槽-Slot', key: 'Slot-0-7-0-8' },
        { label: '主板', value: '主板-MAINFRAME', key: 'MAINFRAME-0-7-0-9' },
        { label: '刀片', value: '刀片-Blade', key: 'Blade-0-7-0-10' },
        { label: 'Raid卡', value: 'Raid卡-Raid', key: 'Raid-0-7-0-11' },
        { label: 'OA模块', value: 'OA模块-OA', key: 'OA-0-7-0-12' },
        { label: '内联模块', value: '内联模块-NETCONNECT', key: 'NETCONNECT-0-7-0-13' },
        { label: '控制器', value: '控制器-Controller', key: 'Controller-0-7-0-14' },
        { label: '温度', value: '温度-Temperature', key: 'Temperature-0-7-0-15' },
        { label: '磁带库', value: '磁带库-TAPE_Libarary', key: 'TAPE_Libarary-0-7-0-16' },
        { label: '光盘库', value: '光盘库-CD_Libarary', key: 'CD_Libarary-0-7-0-17' },
        { label: '加速板', value: '加速板-Accelerator', key: 'Accelerator-0-7-0-18' },
      ],
    }, {
      label: 'IBM服务器',
      value: 'IBM服务器-IBM',
      key: 'IBM-0-7-1',
      children: [
        { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-7-1-0' },
          { label: '内存', value: '内存-Memory', key: 'Memory-0-7-1-1' },
          { label: 'FSP卡', value: 'FSP卡-FSP', key: 'FSP-0-7-1-2' },
          { label: '电源', value: '电源-Power', key: 'Power-0-7-1-3' },
          { label: '风扇', value: '风扇-Fan', key: 'Fan-0-7-1-4' },
          { label: '主板', value: '主板-MAINFRAME', key: 'MAINFRAME-0-7-1-5' },
      ],
    }, {
      label: '华为服务器',
      value: '华为服务器-HuaWei',
      key: 'HuaWei-0-7-2',
      children: [
        { label: 'CPU', value: 'CPU-CPU', key: 'CPU-0-7-2-0' },
          { label: '线缆 ', value: '线缆-Cable', key: 'Cable-0-7-2-1' },
          { label: '设备', value: '设备-Device', key: 'Device-0-7-2-2' },
          { label: '看门狗', value: '看门狗-WatchDog', key: 'WatchDog-0-7-2-3' },
          { label: '管理模块 ', value: '管理模块-MngmntHealth', key: 'MngmntHealth-0-7-2-4' },
          { label: '电池', value: '电池-Battery', key: 'Battery-0-7-2-5' },
          { label: '温度', value: '温度-Temperature', key: 'Temperature-0-7-2-6' },
          { label: '电压 ', value: '电压-Voltage', key: 'Voltage-0-7-2-7' },
          { label: '内存', value: '内存-Memory', key: 'Memory-0-7-2-8' },
          { label: '电源', value: '电源-PowerSupply', key: 'PowerSupply-0-7-2-9' },
          { label: '网口 ', value: '网口-LAN', key: 'LAN-0-7-2-10' },
          { label: '传感器', value: '传感器-FRU', key: 'FRU-0-7-2-11' },
          { label: 'Flash', value: 'Flash-FlashUsage', key: 'FlashUsage-0-7-2-12' },
          { label: '交换板 ', value: '交换板-Lsw', key: 'Lsw-0-7-2-13' },
          { label: 'Port', value: 'Port-PortManagementStatus', key: 'PortManagementStatus-0-7-2-14' },
          { label: '风扇', value: '风扇-Fan', key: 'Fan-0-7-2-15' },
          { label: '硬盘 ', value: '硬盘-HardDisk', key: 'HardDisk-0-7-2-16' },
      ],
    }],
  }]
