 export default  [
	{
		key: 'NodeAlias',
		type: 'string',
		name: 'IP地址(NodeAlias)',
		core: false,
	},
	{
		key: 'Node',
		type: 'string',
		name: '主机名(Node)',
		core: false,
	},
	{
		key: 'AlertGroup',
		type: 'string',
		name: '告警组(AlertGroup)',
		core: false,
	},
	{
		key: 'N_Factory',
		type: 'string',
		name: '告警节点厂商(N_Factory)',
		core: false,
	},
	{
		key: 'Manager',
		type: 'string',
		name: '告警采集器(Manager)',
		core: false,
	},
	{
		key: 'N_AppCode',
		type: 'string',
		name: '应用系统代码(N_AppCode)',
		core: false,
	},
	{
		key: 'N_AppName',
		type: 'string',
		name: '应用系统名称(N_AppName)',
		core: false,
	},
	{
		key: 'OZ_OrgCode',
		type: 'string',
		name: '告警来源(OZ_OrgCode)',
		core: false,
	}, {
		key: 'N_OrgId',
		type: 'string',
		name: '所属机构(N_OrgId)',
		core: false,
	},
	{
		key: 'Acknowledged',
		type: 'string',
		name: '接管状态(Acknowledged)',
		core: false,
	},
	{
		key: 'Agent',
		type: 'string',
		name: '监控代理(Agent)',
		core: false,
	},
	{
		key: 'N_MgtOrg',
		type: 'string',
		name: '管理机构(N_MgtOrg)',
		core: false,
	},
	{
		key: 'Severity',
		type: 'string',
		name: '级别(Severity)',
		core: false,
	},
	{
		key: 'N_MaintainStatus',
		type: 'string',
		name: '维护期状态(N_MaintainStatus)',
		core: false,
	},
	{
		key: 'N_BizArea',
		type: 'string',
		name: '网络区域(N_BizArea)',
		core: false,
	},
	{
		key: 'OZ_OrgName',
		type: 'string',
		name: '采集器所在机构(OZ_OrgName)',
		core: false,
	},
	{
		key: 'N_SubComponent',
		type: 'string',
		name: '告警子类(N_SubComponent)',
		core: false,
	},
	{
		key: 'N_Component',
		type: 'string',
		name: '告警中类(N_Component)',
		core: false,
	},
	{
		key: 'N_ComponentType',
		type: 'string',
		name: '告警大类(N_ComponentType)',
		core: false,
	},
	{
		key: 'N_SummaryCN',
		type: 'string',
		name: '告警详情(N_SummaryCN)',
		core: false,
	},
	{
		key: 'N_PeerPort',
		type: 'string',
		name: '监控工具(N_PeerPort)',
		core: false,
	},
	{
		key: 'N_CustomerSeverity',
		type: 'string',
		name: '级别(N_CustomerSeverity)',
		core: false,
	},
	{
		key: 'AlertKey',
		type: 'string',
		name: '关键字(AlertKey)',
		core: false,
	},
	{
		key: 'n_ObjectDesCr',
		type: 'string',
		name: '对象描述(n_ObjectDesCr)',
		core: false,
	},
]
