export default  [
	{
		title: '1_time',
		dataIndex: 'time',
		width: 150,
		key: 'time',
		render: (text, record) => {
			return new Date(text * 1000).format('yyyy-MM-dd hh:mm:ss')
		},
	}, {
		title: '2_close_flow_count',
		dataIndex: 'close_flow_count',
		width: 150,
		key: 'close_flow_count',
	}, {
		title: '3_concurrent_flow_count',
		dataIndex: 'concurrent_flow_count',
		width: 180,
		key: 'concurrent_flow_count',
	}, {
		title: '4_create_flow_count',
		dataIndex: 'create_flow_count',
		width: 150,
		key: 'create_flow_count',
	}, {
		title: '5_downlink_packet_lost_rate',
		dataIndex: 'downlink_packet_lost_rate',
		width: 200,
		key: 'downlink_packet_lost_rate',
	}, {
		title: '6_downlink_packet_retrans_rate',
		dataIndex: 'downlink_packet_retrans_rate',
		width: 220,
		key: 'downlink_packet_retrans_rate',
	}, {
		title: '7_downlink_tcp_retransmission_packet',
		dataIndex: 'downlink_tcp_retransmission_packet',
		width: 260,
		key: 'downlink_tcp_retransmission_packet',
	}, {
		title: '8_downlink_tcp_segment_lost_packet',
		dataIndex: 'downlink_tcp_segment_lost_packet',
		width: 260,
		key: 'downlink_tcp_segment_lost_packet',
	}, {
		title: '9_netlinkId',
		dataIndex: 'netlinkId',
		width: 150,
		key: 'netlinkId',
	}, {
		title: '10_netsegment_id',
		dataIndex: 'netsegment_id',
		width: 280,
		key: 'netsegment_id',
	}, {
		title: '11_rx_bitps',
		dataIndex: 'rx_bitps',
		width: 150,
		key: 'rx_bitps',
	}, {
		title: '12_rx_byte',
		dataIndex: 'rx_byte',
		width: 150,
		key: 'rx_byte',
	}, {
		title: '13_rx_packet',
		dataIndex: 'rx_packet',
		width: 150,
		key: 'rx_packet',
	}, {
		title: '14_rx_tcp_syn_packet',
		dataIndex: 'rx_tcp_syn_packet',
		width: 200,
		key: 'rx_tcp_syn_packet',
	}, {
		title: '15_rx_tcp_synack_packet',
		dataIndex: 'rx_tcp_synack_packet',
		width: 200,
		key: 'rx_tcp_synack_packet',
	}, {
		title: '16_taskName',
		dataIndex: 'taskName',
		width: 280,
		key: 'taskName',
	}, {
		title: '17_tcp_retransmission_packet',
		dataIndex: 'tcp_retransmission_packet',
		width: 220,
		key: 'tcp_retransmission_packet',
	}, {
		title: '18_tcp_segment_lost_packet',
		dataIndex: 'tcp_segment_lost_packet',
		width: 220,
		key: 'tcp_segment_lost_packet',
	}, {
		title: '19_tcp_syn_packet',
		dataIndex: 'tcp_syn_packet',
		width: 180,
		key: 'tcp_syn_packet',
	}, {
		title: '20_tcp_synack_packet',
		dataIndex: 'tcp_synack_packet',
		width: 180,
		key: 'tcp_synack_packet',
	}, {
		title: '21_alive_flow_count',
		dataIndex: 'alive_flow_count',
		width: 180,
		key: 'alive_flow_count',
	}, {
		title: '22_total_bitps',
		dataIndex: 'total_bitps',
		width: 180,
		key: 'total_bitps',
	}, {
		title: '23_total_byte',
		dataIndex: 'total_byte',
		width: 180,
		key: 'total_byte',
	}, {
		title: '24_total_packet',
		dataIndex: 'total_packet',
		width: 180,
		key: 'total_packet',
	}, {
		title: '25_total_packet_lost_rate',
		dataIndex: 'total_packet_lost_rate',
		width: 220,
		key: 'total_packet_lost_rate',
	}, {
		title: '26_total_packet_retrans_rate',
		dataIndex: 'total_packet_retrans_rate',
		width: 220,
		key: 'total_packet_retrans_rate',
	}, {
		title: '27_tx_bitps',
		dataIndex: 'tx_bitps',
		width: 180,
		key: 'tx_bitps',
	}, {
		title: '28_tx_byte',
		dataIndex: 'tx_byte',
		width: 180,
		key: 'tx_byte',
	}, {
		title: '29_tx_packet',
		dataIndex: 'tx_packet',
		width: 180,
		key: 'tx_packet',
	}, {
		title: '30_tx_tcp_syn_packet',
		dataIndex: 'tx_tcp_syn_packet',
		width: 200,
		key: 'tx_tcp_syn_packet',
	}, {
		title: '31_tx_tcp_synack_packet',
		dataIndex: 'tx_tcp_synack_packet',
		width: 200,
		key: 'tx_tcp_synack_packet',
	}, {
		title: '32_uplink_packet_lost_rate',
		dataIndex: 'uplink_packet_lost_rate',
		width: 220,
		key: 'uplink_packet_lost_rate',
	}, {
		title: '33_uplink_tcp_retransmission_packet',
		dataIndex: 'uplink_tcp_retransmission_packet',
		width: 280,
		key: 'uplink_tcp_retransmission_packet',
	}, {
		title: '34_uplink_tcp_segment_lost_packet',
		dataIndex: 'uplink_tcp_segment_lost_packet',
		width: 280,
		key: 'uplink_tcp_segment_lost_packet',
	},
]
