export const commOutRoutes = [
  {//登录
    path: '/',
    models: () => [import('./models/login'), import('./models/dataDict')],
    component: () => import('./routes/login'),
    exact: true,
  },
  {
    path: "/oauth-sso/entry",
    models: () => [import('./models/entry'), import('./models/dataDict')],
    component: () => import('./routes/oauth-sso/Entry.js'),
    exact: true,
  },
  {
    path: "/oauth-sso/login",
    models: () => [import('./models/entry'), import('./models/dataDict')],
    component: () => import('./routes/oauth-sso/Entry.js'),
    exact: true,
  },
  {//历史告警
    path: '/historyviewGroup',
    models: () => [import('./models/historyviewGroup'), import('./models/historyview'), import('./models/mainRuleInstanceInfo'), 
    import('./components/alarmFromComp/alarmFrom'), import('./components/notifyWayComp/notifyWay'), import('./components/alarmSeverityComp/alarmSeverity'), 
    import('./components/userSelectComp/userSelect'), import('./components/moSelectComp/moSelect'), import('./components/appSelectComp/appSelect'), 
    import('./models/traceBack'),import('./components/alarmModal/alarm'),import('./models/notification'),],
    component: () => import('./routes/historyview'),
    exact: false,
  },
  {//老平台历史告警
    path: '/u1Historyviews',
    models: () => [import('./models/u1HistoryviewGroup'), import('./models/u1Historyview')],
    component: () => import('./routes/u1Historyview/'),
    exact: false,
  }
]

export const commInRoutes = [
  {//用户信息
    path: '/userInfo',
    models: () => [import('./models/userinfo')],
    component: () => import('./routes/user/userinfo'),
    exact: true,
  },
  {//角色管理
    path: '/roles',
    models: () => [import('./models/roles'), import('./models/objectMOsModal')],
    component: () => import('./routes/user/roles/'),
    exact: true,
  },
  {//集群信息
    path: '/zookeeper',
    models: () => [import('./models/zookeeper')],
    component: () => import('./routes/zookeeper'),
    exact: true,
  },

  //监控配置
  {//周期管理
    path: '/timePeriods',
    models: () => [import('./models/periodconfig')],
    component: () => import('./routes/periodconfig/'),
    exact: true,
  },
  {//外表管理
    path: '/lookupGroup',
    models: () => [import('./models/lookupGroup'), import('./models/lookupInfo')],
    component: () => import('./routes/lookupGroup'),
    exact: false,
  },
  {//应用系统管理
    path: '/appCategories',
    models: () => [import('./models/appCategories')],
    component: () => import('./routes/appCategories/'),
    exact: true,
  },
  /* {//通知渠道
    path:'/channel',
    models: () => [import('./models/channel')],
    component: () => import('./routes/channel'),
    exact:true,
  }, */
  {//告警跟踪规则
    path: '/trackTimer',
    models: () => [import('./models/trackTimer')],
    component: () => import('./routes/trackTimer'),
    exact: true,
  },
  {//任务管理
    path: '/jobs',
    models: () => [import('./models/jobs')],
    component: () => import('./routes/jobs'),
    exact: true,
  },

  {//所有监控对象
    path: '/mo',
    models: () => [import('./models/mo')],
    component: () => import('./routes/mo/'),
    exact: true,
  },
  {//监控对象router
    path: '/router',
    models: () => [import('./models/router'), import('./models/interfacer'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./routes/objectGroup/utils/interfaceListComp/interfaceList'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/router'),
    exact: true,
  },
  {//监控对象switcher
    path: '/switcher',
    models: () => [import('./models/switcher'), import('./models/interfacer'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./routes/objectGroup/utils/interfaceListComp/interfaceList'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/switcher'),
    exact: true,
  },
  {//监控对象interfacer
    path: '/interfacer',
    models: () => [import('./models/interfacer'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect')],
    component: () => import('./routes/objectGroup/interfacer'),
    exact: true,
  },
  {//监控对象firewall
    path: '/firewall',
    models: () => [import('./models/firewall'), import('./models/interfacer'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./routes/objectGroup/utils/interfaceListComp/interfaceList'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/firewall'),
    exact: true,
  },
  {//监控对象netmanager
    path: '/netmanager',
    models: () => [import('./models/netmanager'), import('./models/interfacer'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./routes/objectGroup/utils/interfaceListComp/interfaceList'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/netmanager'),
    exact: true,
  },
  {//监控对象f5
    path: '/f5',
    models: () => [import('./models/f5'), import('./models/interfacer'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./routes/objectGroup/utils/interfaceListComp/interfaceList'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/f5'),
    exact: true,
  },
  {//监控对象line
    path: '/line',
    models: () => [import('./models/line'), import('./models/interfacer'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./routes/objectGroup/utils/interfaceListComp/interfaceList'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/line'),
    exact: true,
  },
  {//监控对象branchIp
    path: '/branchIp',
    models: () => [import('./models/branchIp'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/branchIp'),
    exact: true,
  },
  {//监控对象server
    path: '/server',
    models: () => [import('./models/server'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/server'),
    exact: true,
  },
  {//监控对象middleware
    path: '/middleware',
    models: () => [import('./models/middleware'), import('./components/appSelectComp/appSelect'), import('./routes/objectGroup/utils/policyListComp/policyList')],
    component: () => import('./routes/objectGroup/middleware'),
    exact: true,
  },
  {//监控对象database
    path: '/database',
    models: () => [import('./models/database'), import('./components/appSelectComp/appSelect'), import('./routes/objectGroup/utils/policyListComp/policyList')],
    component: () => import('./routes/objectGroup/database'),
    exact: true,
  },
  {//监控对象application
    path: '/application',
    models: () => [import('./models/application'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/application'),
    exact: true,
  },
  {//监控对象os
    path: '/os',
    models: () => [import('./models/os'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/os'),
    exact: true,
  },
  {//监控对象storages
    path: '/storages',
    models: () => [import('./models/storage'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/storage'),
    exact: true,
  },
  {//监控对象hardwareServer
    path: '/hardwareServer',
    models: () => [import('./models/hardwareServer'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/hardwareServer'),
    exact: true,
  },
  {//监控对象cloudequipment
    path: '/cloudequipment',
    models: () => [import('./models/cloudequipment'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/cloudequipment'),
    exact: true,
  },
  {//监控对象specialequipment
    path: '/specialequipment',
    models: () => [import('./models/specialequipment'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/specialequipment'),
    exact: true,
  },
  {//监控对象IP
    path: '/IP',
    models: () => [import('./models/IP'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/IP'),
    exact: true,
  },
  {//监控对象page
    path: '/page',
    models: () => [import('./models/page'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/page'),
    exact: true,
  },
  {//监控对象ssl
    path: '/ssl',
    models: () => [import('./models/ssl'), import('./models/interfacer'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./routes/objectGroup/utils/interfaceListComp/interfaceList'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/ssl'),
    exact: true,
  },
  {//监控对象secDevice
    path: '/secdevice',
    models: () => [import('./models/secDevice'), import('./models/interfacer'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./routes/objectGroup/utils/interfaceListComp/interfaceList'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/secDevice'),
    exact: true,
  },
  {//监控对象dbinst
    path: '/dbinst',
    models: () => [import('./models/dbinst'), import('./components/appSelectComp/appSelect'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect')],
    component: () => import('./routes/objectGroup/dbinst'),
    exact: true,
  },
  {//监控对象 tableSpace
    path: '/dbTableSpace',
    models: () => [import('./models/dbTableSpace'), import('./components/appSelectComp/appSelect'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect')],
    component: () => import('./routes/objectGroup/dbTableSpace'),
    exact: true,
  },
  {//监控对象tableSpacetemp
    path: '/dbTableSpaceTemp',
    models: () => [import('./models/dbTableSpaceTemp'), import('./components/appSelectComp/appSelect'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect')],
    component: () => import('./routes/objectGroup/dbTableSpaceTemp'),
    exact: true,
  },
  {//监控对象username
    path: '/dbUsername',
    models: () => [import('./models/dbUsername'), import('./components/appSelectComp/appSelect'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect')],
    component: () => import('./routes/objectGroup/dbUsername'),
    exact: true,
  },
  {//监控对象 dbService
    path: '/dbService',
    models: () => [import('./models/dbService'), import('./components/appSelectComp/appSelect'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect')],
    component: () => import('./routes/objectGroup/dbService'),
    exact: true,
  },
  {//监控对象dbdatabase
    path: '/dbdatabase',
    models: () => [import('./models/dbDataBase'), import('./components/appSelectComp/appSelect'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect')],
    component: () => import('./routes/objectGroup/dbDataBase'),
    exact: true,
  },
  {//监控对象 fs 文件系统
    path: '/osFs',
    models: () => [import('./models/osFs'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./components/appSelectComp/appSelect'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect')],
    component: () => import('./routes/objectGroup/osFs'),
    exact: true,
  },
  {//监控对象 disk 磁盘
    path: '/osDisk',
    models: () => [import('./models/osDisk'), import('./routes/objectGroup/utils/policyListComp/policyList'), import('./components/appSelectComp/appSelect'), import('./routes/objectGroup/utils/moSingleSelectComp/moSingleSelect')],
    component: () => import('./routes/objectGroup/osDisk'),
    exact: true,
  },
  {//监控对象rulespreview
    path: '/rulespreview',
    models: () => [import('./models/rulesPreview')],
    component: () => import('./routes/rulespreview'),
    exact: true,
  },

  {//监控工具
    path: '/toollist',
    models: () => [import('./models/tool'), import('./models/labelGroup')],
    component: () => import('./routes/tool'),
    exact: true,
  },

  {//EPP管理
    path: '/epp',
    models: () => [import('./models/epp')],
    component: () => import('./routes/epp'),
    exact: true,
  },

  {//EPP屏蔽策略
    path: '/eppPolicy',
    models: () => [import('./models/eppPolicy')],
    component: () => import('./routes/eppPolicy'),
    exact: true,
  },

  {//标签
    path: '/labelGroup',
    models: () => [import('./models/labelGroup'), import('./models/label')],
    component: () => import('./routes/labelGroup'),
    exact: false,
  },

  {//监控指标管理
    path: '/stdIndicatorGroup',
    models: () => [import('./models/stdIndicatorGroup'), import('./models/stdIndicatorsInfo')],
    component: () => import('./routes/stdIndicatorGroup'),
    exact: false,
  },
  {//指标实现管理
    path: '/zabbixItemsGroup',
    models: () => [import('./models/zabbixItemsGroup'), import('./models/zabbixItemsInfo'), import('./models/stdIndicatorGroup'), import('./models/objectGroup'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/zabbixItemsGroup'),
    exact: false,
  },
  {//通知规则管理
    path: '/notification',
    models: () => [import('./models/notification'), import('./models/userinfo'), import('./models/roles'), import('./components/alarmFromComp/alarmFrom'), import('./components/alarmSeverityComp/alarmSeverity'), import('./components/moSelectComp/moSelect'), import('./components/notifyWayComp/notifyWay')],
    component: () => import('./routes/notification/'),
    exact: true,
  },
  {//通知记录查询
    path: '/notficationView',
    models: () => [import('./models/notficationView'), import('./models/userinfo'), import('./components/alarmFromComp/alarmFrom'), import('./components/alarmSeverityComp/alarmSeverity'), import('./components/moSelectComp/moSelect'), import('./components/notifyWayComp/notifyWay')],
    component: () => import('./routes/notficationView/'),
    exact: true,
  },
  {//app消息流水
    path: '/APPinfor',
    models: () => [import('./models/APPinfor'), import('./models/historyview')],
    component: () => import('./routes/APPinfor/'),
    exact: true,
  },

  {//策略实例管理
    path: '/policyInstanceGroup',
    models: () => [import('./models/policyInstanceGroup'), import('./models/policyInstance'), import('./models/object'), import('./models/stdIndicatorGroup')],
    component: () => import('./routes/policy/instanceGroup'),
    exact: false,
  },
  {//策略模板管理
    path: '/policyTempletGroup',
    models: () => [import('./models/policyTempletGroup'), import('./models/policyTemplet'), import('./models/stdIndicatorGroup'), import('./models/labelGroup')],
    component: () => import('./routes/policy/templetGroup'),
    exact: false,
  },
  {//策略规则管理
    path: '/policyRuleGroup',
    models: () => [import('./models/policyRuleGroup'), import('./models/policyRule'), import('./models/objectMOsModal'), import('./models/policyTempletGroup'), import('./models/objectGroup'), import('./models/stdIndicatorGroup'),],
    component: () => import('./routes/policy/ruleGroup'),
    exact: false,
  },
  {//监控实例管理
    path: '/ruleInstanceGroup',
    models: () => [import('./models/ruleInstanceGroup'), import('./models/ruleInstance'), import('./models/objectMOsModal'), import('./models/stdIndicatorGroup')],
    component: () => import('./routes/policy/ruleInstanceGroup'),
    exact: false,
  },
  {//非网络监控实例管理
    path: '/notNetDown',
    models: () => [import('./models/notNetDown')],
    component: () => import('./routes/notNetDown/'),
    exact: true,
  },

  {//网络自服务
    path: '/moWizard',
    models: () => [import('./models/mowizard'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/MOWizard'),
    exact: true,
  },
  {//自动发现
    path: '/discovery',
    models: () => [import('./models/discovery'), import('./models/mowizard'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/discovery'),
    exact: true,
  },
  {
    path: '/discovery/info',
    models: () => [import('./models/discoveryInfoShow')],
    component: () => import('./routes/discovery/info'),
    exact: true,
  },
  {//维护期实例
    path: '/mainRuleInstanceGroup',
    models: () => [import('./models/mainRuleInstanceGroup'), import('./models/mainRuleInstanceInfo'), import('./models/stdIndicatorGroup'), import('./models/objectGroup'), import('./components/userSelectComp/userSelect'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/mainRuleInstanceGroup/'),
    exact: false,
  },
  {//维护期模板
    path: '/maintenanceTempletGroup',
    models: () => [import('./models/maintenanceTempletGroup'), import('./models/mainRuleInstanceInfo'), import('./models/maintenanceTemplet'), import('./components/userSelectComp/userSelect'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/maintenance/templetGroup'),
    exact: false,
  },
  {//我的维护期
    path: '/myMaintenan',
    models: () => [import('./models/mainRuleInstanceInfo'), import('./components/userSelectComp/userSelect'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/maintenance/myMaintenan'),
    exact: true,
  },

  {//报表配置
    path: '/formConfigurationGroup',
    models: () => [import('./models/formConfigurationGroup'), import('./models/formConfiguration')],
    component: () => import('./routes/formConfiguration'),
    exact: false,
  },

  {//总行网络
    path: '/totalnet',
    models: () => [import('./models/totalnet')],
    component: () => import('./routes/totalnet/'),
    exact: true,
  },
  {//分行网络
    path: '/branchnet',
    models: () => [import('./models/branchnet'), import('./models/totalnet')],
    component: () => import('./routes/branchnet/'),
    exact: true,
  },

  {//主界面
    path: '/welcome',
    models: () => [import('./models/welcome')],
    component: () => import('./routes/welcome'),
    exact: true,
  },
  {//iam登录
    path: '/iam',
    models: () => [import('./models/iam'), import('./models/welcome'), import('./models/dataDict')],
    component: () => import('./routes/welcome'),
    exact: true,
  },
  {//公共文档
    path: '/publicDoc',
    models: () => [import('./models/welcome')],
    component: () => import('./routes/publicDoc/'),
    exact: true,
  },
  {//管理员文档
    path: '/privateDoc',
    //models: () => [import('./models/monitor')],
    models: () => [import('./models/welcome')],
    component: () => import('./routes/privateDoc'),
    exact: true,
  },
  {//数据字典
    path: '/dataDict',
    models: () => [import('./models/dataDict'), import('./models/dataDictItem')],
    component: () => import('./routes/dataDict/'),
    exact: true,
  },
  {//实时告警列表
    path: '/oel',
    models: () => [import('./models/oelEventFilter'), import('./models/oelDataSouseset'), import('./models/oel'), import('./models/oelToolset'),
    import('./components/alarmFromComp/alarmFrom'), import('./components/notifyWayComp/notifyWay'), import('./components/alarmSeverityComp/alarmSeverity'), 
     import('./models/eventviews'),import('./components/alarmModal/alarm'),import('./models/notification'), import('./components/moSelectComp/moSelect'),
     import('./components/userSelectComp/userSelect'), import('./components/appSelectComp/appSelect'),  import('./models/mainRuleInstanceInfo'),
     import('./models/historyview')],
    component: () => import('./routes/oel/'),
    exact: true,
  },
  {//告警压缩列表
    path: '/oelCompression',
    models: () => [import('./models/oelEventFilter'), import('./models/oelDataSouseset'), import('./models/oelcompression'), import('./models/oelToolset'), import('./models/eventviews')],
    component: () => import('./routes/oelCompression/'),
    exact: true,
  },
  {//告警提示
    path: '/oelHint',
    models: () => [import('./models/oelEventFilter'), import('./models/oelDataSouseset'), import('./models/oelHint'), import('./models/oelToolset'), import('./models/eventviews')],
    component: () => import('./routes/oelHint/'),
    exact: true,
  },  
  {//服务台实时告警查询
    path: '/monitorview',
    models: () => [import('./models/oelEventFilter'), import('./models/oelDataSouseset'), import('./models/monitorview')],
    component: () => import('./routes/monitorview/'),
    exact: true,
  },
  {//一线实时告警查询
    path: '/frontview',
    models: () => [import('./models/oelEventFilter'), import('./models/oelDataSouseset'), import('./models/frontview')],
    component: () => import('./routes/frontview/'),
    exact: true,
  },
  {//分行实时告警查询
    path: '/branchview',
    models: () => [import('./models/oelEventFilter'), import('./models/oelDataSouseset'), import('./models/branchview')],
    component: () => import('./routes/branchview'),
    exact: true,
  },
  {//总行实时告警
    path: '/centerview',
    models: () => [import('./models/oelEventFilter'), import('./models/oelDataSouseset'), import('./models/centerview')],
    component: () => import('./routes/centerview/'),
    exact: true,
  },
  {//监控维护告警
    path: '/monview',
    models: () => [import('./models/oelEventFilter'), import('./models/oelDataSouseset'), import('./models/monview')],
    component: () => import('./routes/monview/'),
    exact: true,
  },
  {//信用卡一线实时告警查询
    path: '/xykfrontview',
    models: () => [import('./models/oelEventFilter'), import('./models/oelDataSouseset'), import('./models/frontview')],
    component: () => import('./routes/frontview/'),
    exact: true,
  },
  {//未恢复告警查询
    path: '/oelCust',
    models: () => [import('./models/oelEventFilter'), import('./models/oelDataSouseset'), import('./models/oelCust'), import('./models/oelToolset'), import('./models/eventviews')],
    component: () => import('./routes/oelCust/'),
    exact: true,
  },
  {//告警分布图
    path: '/alarmdiagram',
    models: () => [import('./models/distribution'), import('./models/oelEventFilter'), import('./models/oelDataSouseset'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/distribution/'),
    exact: true,
  },
  {//告警跟踪
    path: '/oelTrack',
    models: () => [import('./models/oelTrack')],
    component: () => import('./routes/oelTrack/'),
    exact: true,
  },
  {//性能管理下钻
    path: '/chdlist',
    models: () => [import('./models/chd'), import('./models/objectGroup')],
    component: () => import('./routes/chd/chdlist'),
    exact: true,
  },
  {
    path: '/chdlistall',
    models: () => [import('./models/chd'), import('./models/objectGroup')],
    component: () => import('./routes/chd/chdlistall'),
    exact: true,
  },
  {
    path: '/chdlistresponse',
    models: () => [import('./models/chd'), import('./models/objectGroup')],
    component: () => import('./routes/chd/chdlistresponse'),
    exact: true,
  },
  {
    path: '/chdlistloss',
    models: () => [import('./models/chd'), import('./models/objectGroup')],
    component: () => import('./routes/chd/chdlistloss'),
    exact: true,
  },
  {
    path: '/chdlistcpu',
    models: () => [import('./models/chd'), import('./models/objectGroup')],
    component: () => import('./routes/chd/chdlistcpu'),
    exact: true,
  },
  {
    path: '/chdlistmemery',
    models: () => [import('./models/chd'), import('./models/objectGroup')],
    component: () => import('./routes/chd/chdlistmemery'),
    exact: true,
  },
  {
    path: '/chddetail',
    models: () => [import('./models/interfaceChart'), import('./models/objectGroup')],
    component: () => import('./routes/chd/chddetail'),
    exact: true,
  },
  {//性能页面
    path: '/dashboard',
    models: () => [import('./models/objectGroup'), import('./models/objectMO'),],
    component: () => import('./routes/dashboard'),
    exact: true,
  },
  {//性能首页
    path: '/dashboard/performance',
    models: () => [import('./models/performance'), import('./models/interfaces'), import('./models/monitor'),],
    component: () => import('./routes/dashboard/performance'),
    exact: true,
  },
  {//性能设备清单    因只有现场有数据,性能内部路由暂停堆叠
    path: '/dashboard/interfaces',
    models: () => [import('./models/interfaces'), import('./models/oelEventFilter'), import('./models/oelDataSouseset'), import('./models/oel'), import('./models/oelToolset'), import('./models/eventviews')],
    component: () => import('./routes/dashboard/interfaces'),
    exact: true,
  },
  {//性能告警
    path: '/dashboard/events',
    models: () => [import('./models/events'), import('./models/performance')],
    component: () => import('./routes/dashboard/events'),
    exact: true,
  },
  {//性能响应时间
    path: '/dashboard/Response',
    models: () => [import('./models/performance')],
    component: () => import('./routes/dashboard/response'),
    exact: true,
  },
  {//性能丢包率
    path: '/dashboard/Loss',
    models: () => [import('./models/performance')],
    component: () => import('./routes/dashboard/loss'),
    exact: true,
  },
  {//性能CPU
    path: '/dashboard/CPU',
    models: () => [import('./models/performance')],
    component: () => import('./routes/dashboard/cpu'),
    exact: true,
  },
  {//性能内存
    path: '/dashboard/Memory',
    models: () => [import('./models/performance')],
    component: () => import('./routes/dashboard/memory'),
    exact: true,
  },
  {//性能discard和CRC error
    path: '/dashboard/Discard_error',
    models: () => [import('./models/performance')],
    component: () => import('./routes/dashboard/discard_error'),
    exact: true,
  },
  {//网络性能-外联专线
    path: '/dashboard/netLine',
    models: () => [import('./models/netLine')],
    component: () => import('./routes/dashboard/netLine'),
    exact: true,
  },
  {
    path: '/dashboard/netLinePage',
    models: () => [import('./models/netLinePage')],
    component: () => import('./routes/netLinePage'),
    exact: true,
  },
  {//网络防火墙集中监控
    path: '/dashboard/bizarea',
    models: () => [import('./models/netBizareaFirewall')],
    component: () => import('./routes/netBizareaFirewall'),
    exact: true,
  },
  {
    path: '/netfireWall',
    models: () => [import('./models/netfireWall')],
    component: () => import('./routes/netfireWall'),
    exact: true,
  },
  {//负载均衡集中监控
    path: '/dashboard/f5Monitoring',
    models: () => [import('./models/f5Monitoring')],
    component: () => import('./routes/f5Monitoring'),
    exact: true,
  },
  {//实时监控
    path: '/dashboard/internetBank',
    models: () => [import('./models/internetBank')],
    component: () => import('./routes/internetBank'),
    exact: true,
  },
  {//npmLog日志  隐藏
    path: '/npmLog',
    models: () => [import('./models/npmLog')],
    component: () => import('./routes/npmLog/'),
    exact: true,
  },
  {//性能故障
    path: '/faultList',
    models: () => [import('./models/faultList')],
    component: () => import('./routes/faultList'),
    exact: true,
  },
  {//网络环路
    path: '/dashboard/customMonitor',
    models: () => [import('./models/customMonitor')],
    component: () => import('./routes/customMonitor'),
    exact: true,
  },
  {//数据中心互联区
    path: '/dataCenterTransaction',
    models: () => [import('./models/dataCenterTransaction')],
    component: () => import('./routes/dataCenterTransaction'),
    exact: true,
  },
  {//告警追溯
    path: '/traceBack',
    models: () => [import('./models/traceBack')],
    component: () => import('./routes/historyviewInfo/traceBack/'),
    exact: true,
  },
  {//日志审计管理
    path: '/auditLog',
    models: () => [import('./models/auditLog')],
    component: () => import('./routes/auditLog'),
    exact: true,
  },
  {//SSL
    path: '/dashboard/singleSSL',
    models: () => [import('./models/singleSSL')],
    component: () => import('./routes/singleSSL'),
    exact: true,
  },
  {//SSL
    path: '/singleSSLChar',
    models: () => [import('./models/singleSSLChar')],
    component: () => import('./routes/singleSSLChar'),
    exact: true,
  },
  {//SSL 集群
    path: '/colonySSL',
    models: () => [import('./models/colonySSL')],
    component: () => import('./routes/colonySSL'),
    exact: true,
  },
  {//QPS性能曲线
    path: '/dashboard/qps',
    models: () => [import('./models/qps')],
    component: () => import('./routes/qps'),
    exact: true,
  },
  {// 全行网络日志查询
    path: '/qhNetLog',
    models: () => [import('./models/qhNetLog')],
    component: () => import('./routes/qhNetLog'),
    exact: true,
  },
  {//监控对象urlDns
    path: '/urlDns',
    models: () => [import('./models/urlDns'), import('./components/appSelectComp/appSelect')],
    component: () => import('./routes/objectGroup/urlDns'),
    exact: true,
  },
  {//采集器运行管理
    path: '/collector',
    models: () => [import('./models/collector')],
    component: () => import('./routes/collector'),
    exact: true,
  },
]
