
export default {
    id:'EGroup',
    name:'中国光大集团',
    ename:'China Everbright Group',
    tecName:'中国光大集团  © 2020',
    shortName:'光大集团',
    ZH:'光大集团Z',
    FH:'光大集团F',
    QH:'集团重要业务',
    version:'v20200925.01',
    //linkUrl:'/src/components/Layout/EGroupCeb.ico',
    echatID:'光大E信',
    echatRequired: true,
    calc:'下发计算',
    calcInfo:'下发部分',
    calcAlert:'正在计算策略规则信息，请稍后...',
    calcError:'请至少选择一项进行下发！',
    eCebIco:'EGroupCeb.ico',
    eLogoSlider:'EGB.png',
    totalnetZH:'光大集团',
    timeoutAlarm:'http://10.1.7.8:9090/itumpsub/com/resoft/itDomain/itDomain.jsp',   
    formPresentationGroup: 'http://25.4.0.16/itumpsub/app/PB_ReportCenter.jsp',
    systemsManagement: 'http://25.4.0.19:3000/d/WcjoDU_Wz/cao-zuo-xi-tong-main-ban?orgId=1',
    evaluate: 'http://10.218.32.72/d/G3nsb5qiz/jian-kong-ping-jie-shi-tu?orgId=1',
    profile: 'http://10.218.32.72/d/k9T3Uf3mk/jian-kong-dang-an-cha-xun-quan-bu-ying-yong-xi-tong?orgId=1',
    zhNetwork: 'http://10.1.71.146/ebank/foreign/index.html?apikey=e10adc3949ba59abbe56e057f2gg88dd#/network-alert-logs',
    platOper: 'https://10.218.34.47:5601/app/kibana#/management/elasticsearch/index_management/indices?_g=()', 
    monitorBranch: 'http://10.218.32.75:9090/itumpsub/com/resoft/epay/ebmcpMap/ebmcpMarkPoint.jsp',
    seeModal: 'http://10.218.32.72/d/ceb_app_tran_baseline/guang-da-yin-xing-_ying-yong-xi-tong-jiao-yi-ji-xian',
    // esUser:'Basic ZWxhc3RpYzp1bXBfMjAxOQ==',
    esUser:'Basic ZWxhc3RpYzpFYnVtcF8yMDIy',
    firstSecAreaLabel1:'光大集团一',
    firstSecAreaLabel2:'光大集团二',
    cmdbUrl:'http://itsm.cebbank.com:8080/eoms4',
    welcomeDisplay:'none',
}
